<a href="https://colab.research.google.com/github/maneeha/KGLLM/blob/main/Eunning_GraphRAG_v2_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GraphRAG Implementation with LlamaIndex - V2

[GraphRAG (Graphs + Retrieval Augmented Generation)](https://www.microsoft.com/en-us/research/project/graphrag/) combines the strengths of Retrieval Augmented Generation (RAG) and Query-Focused Summarization (QFS) to effectively handle complex queries over large text datasets. While RAG excels in fetching precise information, it struggles with broader queries that require thematic understanding, a challenge that QFS addresses but cannot scale well. GraphRAG integrates these approaches to offer responsive and thorough querying capabilities across extensive, diverse text corpora.

This notebook provides guidance on constructing the GraphRAG pipeline using the LlamaIndex PropertyGraph abstractions using Neo4J.

This notebook updates the GraphRAG pipeline to v2. If you haven’t checked v1 yet, you can find it [here](https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/cookbooks/GraphRAG_v1.ipynb). Following are the updates to the existing implementation:

1. Integrate with Neo4J Graph database.
2. Embedding based retrieval.

## Installation

`graspologic` is used to use hierarchical_leiden for building communities.

In [ ]:
!pip install llama-index llama-index-graph-stores-neo4j graspologic numpy==1.24.4 scipy==1.12.0 future -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.1/176.1 kB 6.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.9/256.9 kB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.2/84.2 kB 6.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 71.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 104.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.4/38.4 MB 59.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.9/44.9 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 65.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 84.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 365.2/365.2 kB 31.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.3/165.3 kB 16.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 77.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 312.3/312.3 kB 28.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 60.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.7/261.7 kB 25.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 27.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 64.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 4.9 MB/s eta 0:00:00
  Building wheel for graspologic (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jaxlib 0.5.1 requires numpy>=1.25, but you have numpy 1.24.4 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 1.24.4 which is incompatible.
treescope 0.1.9 requires numpy>=1.25.2, but you have numpy 1.24.4 which is incompatible.
blosc2 3.2.0 requires numpy>=1.26, but you have numpy 1.24.4 which is incompatible.
jax 0.5.2 requires numpy>=1.25, but you have numpy 1.24.4 which is incompatible.
pymc 5.20.1 requires numpy>=1.25.0, but you have numpy 1.24.4 which is incompatible.

In [ ]:
import os
import pandas as pd
from llama_index.core import Document

In [ ]:
!pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.11.5-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 kB 2.0 MB/s eta 0:00:00
Collecting pdfminer.six==20231228 (from pdfplumber)
  Downloading pdfminer.six-20231228-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (11.1.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 4.7 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20231228->pdfplumber) (3.4.1)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20231228->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber) (2.22)
Downloading pdfplumber-0.11.5-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 kB 6.1 MB/s eta 0:00:00
Downloading pdfminer.six-20231228-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 66.3 MB/s eta 0:00:00
Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 99.4 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20231228 pdfplumber-0.11.5 pypdfium2-4.30.1

In [ ]:
import pdfplumber

## Load Data

We will use a sample news article dataset retrieved from Diffbot, which Tomaz has conveniently made available on GitHub for easy access.

The dataset contains 2,500 samples; for ease of experimentation, we will use 50 of these samples, which include the `title` and `text` of news articles.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import pdfplumber
from tqdm import tqdm

# Initialize an empty list to hold the documents
documents = []

# Specify the directory containing your PDF files
pdf_dir = '/content/drive/MyDrive/refined/content/test1'

# Get a list of PDF files in the directory
pdf_files = [filename for filename in os.listdir(pdf_dir) if filename.endswith('.pdf')]

# Loop through all PDF files in the specified directory with tqdm
for filename in tqdm(pdf_files, desc="Processing PDF files"):
    pdf_path = os.path.join(pdf_dir, filename)

    # Open and read the PDF file
    with pdfplumber.open(pdf_path) as pdf:
        for page in tqdm(pdf.pages, desc=f"Processing pages of {filename}", leave=False):
            text = page.extract_text()
            if text:  # Check if text was extracted
                documents.append(Document(text=text))

Processing PDF files:   0%|          | 0/2 [00:00<?, ?it/s]
Processing pages of file1.pdf:   0%|          | 0/5 [00:00<?, ?it/s]
Processing pages of file1.pdf:  20%|██        | 1/5 [00:00<00:01,  2.08it/s]
Processing pages of file1.pdf:  40%|████      | 2/5 [00:00<00:00,  3.32it/s]
Processing pages of file1.pdf:  60%|██████    | 3/5 [00:00<00:00,  3.14it/s]
Processing pages of file1.pdf:  80%|████████  | 4/5 [00:01<00:00,  3.23it/s]
Processing pages of file1.pdf: 100%|██████████| 5/5 [00:01<00:00,  3.44it/s]
Processing PDF files:  50%|█████     | 1/2 [00:02<00:02,  2.10s/it]
Processing pages of file2.pdf:   0%|          | 0/8 [00:00<?, ?it/s]
Processing pages of file2.pdf:  12%|█▎        | 1/8 [00:00<00:01,  5.77it/s]
Processing pages of file2.pdf:  25%|██▌       | 2/8 [00:00<00:01,  3.38it/s]
Processing pages of file2.pdf:  38%|███▊      | 3/8 [00:00<00:01,  4.52it/s]
Processing pages of file2.pdf:  50%|█████     | 4/8 [00:00<00:00,  5.22it/s]
Processing pages of file2.pdf:  62%|██████▎   | 5/8 [00:00<00:00,  6.13it/s]
Processing pages of file2.pdf:  75%|███████▌  | 6/8 [00:01<00:00,  4.38it/s]
Processing pages of file2.pdf:  88%|████████▊ | 7/8 [00:01<00:00,  4.26it/s]
Processing PDF files: 100%|██████████| 2/2 [00:04<00:00,  2.32s/it]

Prepare documents as required by LlamaIndex

In [ ]:
len(documents)

13

In [ ]:
documents[1]

Document(id_='1fb7e3b3-92cf-40a5-8797-4ddd1b9853c5', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text_resource=MediaResource(embeddings=None, data=None, text="P.J. Burrows, P.J. Gray, A-L. Kinmonth, et al. Original papers\nResults The age distribution at diagnosis of patients in each treat-\nment group is shown in Figure l(b). Although non-insulin-\nPrevalence\ndependentdiabeteswasusuallydiagnosedinlatemiddleageand\nA total of 431 diabetic patients were identified, giving a insulin-dependent diabetes in the young, 110o ofnon-insulin-\nprevalenceof0.85%o.Amongindividualpractices,theprevalence\ndependentdiabeticspresentedundertheageof40yearsand 10%\nofdiabetes varied from 0.6%/o to 1.2%, being greatest in those ofinsulin-dependent diabeticspresentedovertheageof50years.\npractices withthegreatestproportion ofpatients over75years\nof age. There was a slight excess of male patients (233:198).\nPre-treatment blood glucose\nTreatment groups\nApre-treatment bloodglucose level was found in the notes of\nThe patients were classified into three treatment groups: 287 266(621o)patients. Themeanbloodglucoselevels(± standard\n(67%)patientshadbeentreatedwithoutinsulinsincediagnosis deviations) were:\n(non-insulin-dependentdiabetics). Ofthese, 83wereondietalone\nand 204 were onoral hypoglycaemic drugs. Eighty five (20%) Non-insulin-dependent diabetics 16.2 ± 6.1 mM (n=197);\npatientshadbeenoninsulinfromthetimeofdiagnosis(insulin- Insulin-treated diabetics 16.8 ± 4.5 mM (n=27);\ndependent diabetics). A group of 54 patients (13%o) who had Insulin-dependent diabetics 25.9 ± 9.3 mM (n=42).\nbeen started on insulin at least a month after diagnosis were Three non-insulin-dependent diabetic patients were identified\nclassified separately as 'insulin-treated diabetics. Initial treat- in whom the diagnosis ofdiabetes had apparently been made\nment was not clear fromthe records ofthe remaining five pa- onthebasisofrandombloodglucoseconcentrationslowerthan\ntients taking insulin, who were excluded from further analysis\n11 mM.\nby the above treatment groups.\nPresentation\nAge\nTheagedistributionofallpatientsinJuly 1984dividedbytreat- The method ofpresentation, where known, in the three treat-\nmentgroupisshowninFigure l(a). Eighty-sixpercentofnon- ment groups is shown in Table 1. In each ofthe three groups,\ninsulin-dependent diabetics weremorethan 50yearsold, com- most patients presented with primary symptoms of diabetes\npared with 30%o of insulin-dependent diabetics. The insulin- (polyuria,polydipsia, withorwithoutweightloss), ketoacidosis,\ntreated group closely resembled the non-insulin-dependent associated infections (candiasis, recurrent skin sepsis,\ndiabetic group with 76%o over 50 years old.\nbalanitis/vaginitis)orcomplications(includingretinopathy, cata-\nract, neuropathy). TWenty (24%) of the insulin-dependent\ndiabeticpatientspresentedwithclinicalketoacidosis. Ofthenon-\nla)Present gedistribution lb}Agedistributionatdiagnosis insulin-dependent diabetic patients 42% presented without\nspecific symptoms, and in this group the diagnosis was made\n100 Non4inoulin-desendent Non-insulin-dependent\ndbstics n=1287 diabetics in=287) mainlyduringroutinetests (forinstanceatinsuranceexamina-\n80 Meanage - Meanage = tions) or while under investigation for other conditions.\n65 ..(SD 13yr. 58t(5SD)1 3yr. Ofthe384patientswheretheplaceofdiagnosiswasknown,\n60\n73% werediagnosedingeneralpractice. However,alargerpro-\n40 portion of insulin-dependent diabetics (86%) than of non-\ninsulin-dependent diabetics (70%) or insulin-treated diabetics\n20\n0 Table 1.Modeofpresentation (whereknown)inthethreetreatment\n20 ksulin-treted - hsulin-treated groups of diabetic patients.\ndiabetics(n=541 diabeticsIn=541\nNumber (%) of diabetics\n.S° s15 M 58ea ±n 1a 4ge\nyr.\n' 4M 6ea *n 1a 3g ye r.-\n0 Non-insulin- Insulin- Insulin-\n°10 Presentation dependent treated dependent\n.5\nZ 5.. Symptomatic\nPrimary symptoms/\n0I ketoacidosis 71 30 60\n30 dI in as bu el ti in c- sde (p nend 8e 5n )t dI in as bu el ti in c- sde Ip ne =nd 8e 5n 1t A Cs hrs oo nc ii cat ce od mpi ln ife cc at ti io on ns\ns\n6 11\n8\n4\n2\n05\n20f :* .4M 0ea *n 1a 8ge yr.= Total 150 (58) 36 (77) 65 (94)\nAsymptomatic\n10\nRisk factors present 29 2 1\nUnrelated conditions 58 1 1\nRoutine examinations 21 8 2\n01\nTotal 108 (42) 11 (23) 4 (6)\nAge(years)\nTotal (n=374) 258 (100) 47 (100) 69 (100)\nFigure 1.Agedistributiornofalldiabeticpatientsbytreatmentgroup\nshowing (a) present age distribution and (b) age distribution at Presentation unknown\ndiagnosis. (n=52) 29 7 16\n66 Journal of the Royal College of General Practitioners, February 1987", path=None, url=None, mimetype=None), image_resource=None, audio_resource=None, video_resource=None, text_template='{metadata_str}\n\n{content}')

## Setup API Key and LLM

In [ ]:
!pip install llama-index-embeddings-huggingface
!pip install llama-index-llms-huggingface

Collecting llama-index-embeddings-huggingface
  Downloading llama_index_embeddings_huggingface-0.5.2-py3-none-any.whl.metadata (767 bytes)
Requirement already satisfied: huggingface-hub>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.28.1)
Requirement already satisfied: llama-index-core<0.13.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-embeddings-huggingface) (0.12.23.post2)
Requirement already satisfied: sentence-transformers>=2.6.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-embeddings-huggingface) (3.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2024.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.12.2)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.11.13)
Requirement already satisfied: SQLAlchemy>=1.4.49 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (2.0.38)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.2.18)
Requirement already satisfied: dirtyjson<2.0.0,>=1.0.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.0.8)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.2.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.28.1)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (3.4.2)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.24.4)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (11.1.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (2.10.6)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (9.0.0)
Requirement already satisfied: tiktoken>=0.3.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.9.0)
Requirement already satisfied: typing-inspect>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.9.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.17.2)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (4.48.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.5.1+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.12.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.18.3)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (2024.11.6)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2025.1.31)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (3.1.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.3.0)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.5.3)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect>=0.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.0.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (3.26.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.14.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.5.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.0.2)
Downloading llama_index_embeddings_huggingface-0.5.2-py3-none-any.whl (8.9 kB)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 115.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 85.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 55.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 11.3 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 39.8 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 18.0 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.5 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 96.9 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, llama-index-embeddings-huggingface
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed llama-index-embeddings-huggingface-0.5.2 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127
Collecting llama-index-llms-huggingface
  Downloading llama_index_llms_huggingface-0.4.2-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-huggingface) (0.28.1)
Requirement already satisfied: llama-index-core<0.13.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-huggingface) (0.12.23.post2)
Collecting text-generation<0.8.0,>=0.7.0 (from llama-index-llms-huggingface)
  Downloading text_generation-0.7.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: torch<3.0.0,>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-huggingface) (2.5.1+cu124)
Requirement already satisfied: transformers<5.0.0,>=4.37.0 in /usr/local/lib/python3.11/dist-packages (from transformers[torch]<5.0.0,>=4.37.0->llama-index-llms-huggingface) (4.48.3)

In [ ]:
# from llama_index.llms.ollama import Ollama
# llm = Ollama(model="llama3.2", request_timeout=100000.0)

In [ ]:
# from llama_index.embeddings.ollama import OllamaEmbedding

# embed_model = OllamaEmbedding(
#     model_name="nomic-embed-text:latest",
#     base_url="http://localhost:11434",
#     ollama_additional_kwargs={"mirostat": 0},
# )

In [ ]:
embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-m3",
    device='cpu'  # Change 'cuda' to 'cpu'
)

NameError: name 'HuggingFaceEmbedding' is not defined

In [ ]:
import nest_asyncio
nest_asyncio.apply()

from llama_index.llms.huggingface import HuggingFaceLLM
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings, SimpleDirectoryReader, PropertyGraphIndex
from llama_index.graph_stores.neo4j import Neo4jPropertyGraphStore

# Configure Qwen2.5-7B-Instruct model
model_name = "Qwen/Qwen2.5-7B-Instruct"

llm = HuggingFaceLLM(
    model_name=model_name,
    tokenizer_name=model_name,
    device_map="auto",
    max_new_tokens=1024,
    model_kwargs={
        "torch_dtype": "auto",
        "trust_remote_code": True
    },
    tokenizer_kwargs={
        "trust_remote_code": True,
        "pad_token": "<|endoftext|>"
    },
    generate_kwargs={
        "do_sample": True,
        "temperature": 0.7,
        "repetition_penalty": 1.1
    },
    # Qwen2.5 specific chat template formatting
    query_wrapper_prompt="""<|im_start|>system
    You are a helpful assistant.<|im_end|>
<|im_start|>user
{query_str}<|im_end|>
<|im_start|>assistant"""
)

# Keep the rest of your existing configuration
embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-m3",
    device='cuda',
)

Settings.llm = llm
Settings.embed_model = embed_model

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/3.95G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/3.56G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [ ]:
!pip install llama-index-embeddings-huggingface

Requirement already satisfied: llama-index-embeddings-huggingface in /usr/local/lib/python3.11/dist-packages (0.5.2)
Requirement already satisfied: huggingface-hub>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.28.1)
Requirement already satisfied: llama-index-core<0.13.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-embeddings-huggingface) (0.12.23.post2)
Requirement already satisfied: sentence-transformers>=2.6.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-embeddings-huggingface) (3.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2024.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.12.2)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.11.13)
Requirement already satisfied: SQLAlchemy>=1.4.49 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (2.0.38)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.2.18)
Requirement already satisfied: dirtyjson<2.0.0,>=1.0.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.0.8)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.2.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.28.1)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (3.4.2)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.24.4)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (11.1.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (2.10.6)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (9.0.0)
Requirement already satisfied: tiktoken>=0.3.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.9.0)
Requirement already satisfied: typing-inspect>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.9.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.17.2)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (4.48.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.5.1+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.12.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.18.3)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (2024.11.6)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2025.1.31)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (3.1.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.3.1.170)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.4.127)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.3.0)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.5.3)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect>=0.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.0.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (3.26.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (0.14.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.5.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.0.2)

In [ ]:
!pip install llama-index

Requirement already satisfied: llama-index in /usr/local/lib/python3.11/dist-packages (0.12.23)
Requirement already satisfied: llama-index-agent-openai<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.4.6)
Requirement already satisfied: llama-index-cli<0.5.0,>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.4.1)
Requirement already satisfied: llama-index-core<0.13.0,>=0.12.23 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.12.23.post2)
Requirement already satisfied: llama-index-embeddings-openai<0.4.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.3.1)
Requirement already satisfied: llama-index-indices-managed-llama-cloud>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.6.8)
Requirement already satisfied: llama-index-llms-openai<0.4.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.3.25)
Requirement already satisfied: llama-index-multi-modal-llms-openai<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.4.3)
Requirement already satisfied: llama-index-program-openai<0.4.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.3.1)
Requirement already satisfied: llama-index-question-gen-openai<0.4.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.3.0)
Requirement already satisfied: llama-index-readers-file<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.4.6)
Requirement already satisfied: llama-index-readers-llama-parse>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.4.0)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.11/dist-packages (from llama-index) (3.9.1)
Requirement already satisfied: openai>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (1.61.1)
Requirement already satisfied: PyYAML>=6.0.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (6.0.2)
Requirement already satisfied: SQLAlchemy>=1.4.49 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.23->llama-index) (2.0.38)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.6 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (3.11.13)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.2.18)
Requirement already satisfied: dirtyjson<2.0.0,>=1.0.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.0.8)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (2024.10.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (0.28.1)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (3.4.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.24.4)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (11.1.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (2.10.6)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (2.32.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (9.0.0)
Requirement already satisfied: tiktoken>=0.3.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (0.9.0)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (4.67.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (4.12.2)
Requirement already satisfied: typing-inspect>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (0.9.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.17.2)
Requirement already satisfied: llama-cloud<0.2.0,>=0.1.13 in /usr/local/lib/python3.11/dist-packages (from llama-index-indices-managed-llama-cloud>=0.4.0->llama-index) (0.1.14)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (4.13.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.2.2)
Requirement already satisfied: pypdf<6.0.0,>=5.1.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (5.3.1)
Requirement already satisfied: striprtf<0.0.27,>=0.0.26 in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (0.0.26)
Requirement already satisfied: llama-parse>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-llama-parse>=0.4.0->llama-index) (0.6.4.post1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (2024.11.6)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (2.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (1.18.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4<5.0.0,>=4.12.3->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.6)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.11/dist-packages (from llama-cloud<0.2.0,>=0.1.13->llama-index-indices-managed-llama-cloud>=0.4.0->llama-index) (2025.1.31)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.23->llama-index) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.23->llama-index) (1.0.7)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.23->llama-index) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.13.0,>=0.12.23->llama-index) (0.14.0)
Requirement already satisfied: llama-cloud-services>=0.6.4 in /usr/local/lib/python3.11/dist-packages (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index) (0.6.5)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.14.0->llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.14.0->llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (0.8.2)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai>=1.14.0->llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.23->llama-index) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.23->llama-index) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31.0->llama-index-core<0.13.0,>=0.12.23->llama-index) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31.0->llama-index-core<0.13.0,>=0.12.23->llama-index) (2.3.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.23->llama-index) (3.1.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect>=0.8.0->llama-index-core<0.13.0,>=0.12.23->llama-index) (1.0.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json->llama-index-core<0.13.0,>=0.12.23->llama-index) (3.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2025.1)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from llama-cloud-services>=0.6.4->llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index) (1.0.1)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.11/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->llama-index-core<0.13.0,>=0.12.23->llama-index) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (1.17.0)

In [ ]:
!pip install --upgrade llama-index

Requirement already satisfied: llama-index in /usr/local/lib/python3.11/dist-packages (0.12.23)
Requirement already satisfied: llama-index-agent-openai<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.4.6)
Requirement already satisfied: llama-index-cli<0.5.0,>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.4.1)
Requirement already satisfied: llama-index-core<0.13.0,>=0.12.23 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.12.23.post2)
Requirement already satisfied: llama-index-embeddings-openai<0.4.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.3.1)
Requirement already satisfied: llama-index-indices-managed-llama-cloud>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.6.8)
Requirement already satisfied: llama-index-llms-openai<0.4.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.3.25)
Requirement already satisfied: llama-index-multi-modal-llms-openai<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.4.3)
Requirement already satisfied: llama-index-program-openai<0.4.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.3.1)
Requirement already satisfied: llama-index-question-gen-openai<0.4.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.3.0)
Requirement already satisfied: llama-index-readers-file<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.4.6)
Requirement already satisfied: llama-index-readers-llama-parse>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from llama-index) (0.4.0)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.11/dist-packages (from llama-index) (3.9.1)
Requirement already satisfied: openai>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (1.61.1)
Requirement already satisfied: PyYAML>=6.0.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (6.0.2)
Requirement already satisfied: SQLAlchemy>=1.4.49 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.23->llama-index) (2.0.38)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.6 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (3.11.13)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.2.18)
Requirement already satisfied: dirtyjson<2.0.0,>=1.0.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.0.8)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (2024.10.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (0.28.1)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (3.4.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.24.4)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (11.1.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (2.10.6)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (2.32.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (9.0.0)
Requirement already satisfied: tiktoken>=0.3.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (0.9.0)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (4.67.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (4.12.2)
Requirement already satisfied: typing-inspect>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (0.9.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.23->llama-index) (1.17.2)
Requirement already satisfied: llama-cloud<0.2.0,>=0.1.13 in /usr/local/lib/python3.11/dist-packages (from llama-index-indices-managed-llama-cloud>=0.4.0->llama-index) (0.1.14)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (4.13.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.2.2)
Requirement already satisfied: pypdf<6.0.0,>=5.1.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (5.3.1)
Requirement already satisfied: striprtf<0.0.27,>=0.0.26 in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (0.0.26)
Requirement already satisfied: llama-parse>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-llama-parse>=0.4.0->llama-index) (0.6.4.post1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (2024.11.6)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (2.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.23->llama-index) (1.18.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4<5.0.0,>=4.12.3->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.6)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.11/dist-packages (from llama-cloud<0.2.0,>=0.1.13->llama-index-indices-managed-llama-cloud>=0.4.0->llama-index) (2025.1.31)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.23->llama-index) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.23->llama-index) (1.0.7)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.23->llama-index) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.13.0,>=0.12.23->llama-index) (0.14.0)
Requirement already satisfied: llama-cloud-services>=0.6.4 in /usr/local/lib/python3.11/dist-packages (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index) (0.6.5)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.14.0->llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.14.0->llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (0.8.2)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai>=1.14.0->llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.23->llama-index) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.23->llama-index) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31.0->llama-index-core<0.13.0,>=0.12.23->llama-index) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31.0->llama-index-core<0.13.0,>=0.12.23->llama-index) (2.3.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.23->llama-index) (3.1.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect>=0.8.0->llama-index-core<0.13.0,>=0.12.23->llama-index) (1.0.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json->llama-index-core<0.13.0,>=0.12.23->llama-index) (3.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2025.1)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from llama-cloud-services>=0.6.4->llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index) (1.0.1)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.11/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->llama-index-core<0.13.0,>=0.12.23->llama-index) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (1.17.0)

In [ ]:
!pip install llama-index-llms-huggingface

Collecting llama-index-llms-huggingface
  Downloading llama_index_llms_huggingface-0.4.2-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-huggingface) (0.28.1)
Requirement already satisfied: llama-index-core<0.13.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-huggingface) (0.12.23.post2)
Collecting text-generation<0.8.0,>=0.7.0 (from llama-index-llms-huggingface)
  Downloading text_generation-0.7.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: torch<3.0.0,>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-huggingface) (2.5.1+cu124)
Requirement already satisfied: transformers<5.0.0,>=4.37.0 in /usr/local/lib/python3.11/dist-packages (from transformers[torch]<5.0.0,>=4.37.0->llama-index-llms-huggingface) (4.48.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->llama-index-llms-huggingface) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->llama-index-llms-huggingface) (2024.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->llama-index-llms-huggingface) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->llama-index-llms-huggingface) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->llama-index-llms-huggingface) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->llama-index-llms-huggingface) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->llama-index-llms-huggingface) (4.12.2)
Requirement already satisfied: SQLAlchemy>=1.4.49 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (2.0.38)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.6 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (3.11.13)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.2.18)
Requirement already satisfied: dirtyjson<2.0.0,>=1.0.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.0.8)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.2.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (0.28.1)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (3.4.2)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.24.4)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (11.1.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (2.10.6)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (9.0.0)
Requirement already satisfied: tiktoken>=0.3.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (0.9.0)
Requirement already satisfied: typing-inspect>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (0.9.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.17.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch<3.0.0,>=2.1.2->llama-index-llms-huggingface) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch<3.0.0,>=2.1.2->llama-index-llms-huggingface) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.37.0->transformers[torch]<5.0.0,>=4.37.0->llama-index-llms-huggingface) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.37.0->transformers[torch]<5.0.0,>=4.37.0->llama-index-llms-huggingface) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.37.0->transformers[torch]<5.0.0,>=4.37.0->llama-index-llms-huggingface) (0.5.3)
Requirement already satisfied: accelerate>=0.26.0 in /usr/local/lib/python3.11/dist-packages (from transformers[torch]<5.0.0,>=4.37.0->llama-index-llms-huggingface) (1.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate>=0.26.0->transformers[torch]<5.0.0,>=4.37.0->llama-index-llms-huggingface) (5.9.5)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (2.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.18.3)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.23.0->llama-index-llms-huggingface) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.23.0->llama-index-llms-huggingface) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.23.0->llama-index-llms-huggingface) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.23.0->llama-index-llms-huggingface) (2025.1.31)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (3.1.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect>=0.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.0.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (3.26.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (0.14.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch<3.0.0,>=2.1.2->llama-index-llms-huggingface) (3.0.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-huggingface) (1.3.1)
Downloading llama_index_llms_huggingface-0.4.2-py3-none-any.whl (11 kB)
Downloading text_generation-0.7.0-py3-none-any.whl (12 kB)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.7 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 13.3 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 15.9 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 31.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 762.4 kB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.0 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.7 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.3 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 64.4 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, text-generation, nvidia-cusolver-cu12, llama-index-llms-huggingface
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed llama-index-llms-huggingface-0.4.2 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 text-generation-0.7.0

In [ ]:
import torch
print(torch.cuda.is_available())

False

In [ ]:
embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-m3",
    device='cpu'  # Change 'cuda' to 'cpu'
)

In [ ]:
#from llama_index.llms.huggingface import HuggingFaceLLM

In [ ]:
llm.complete("Hello").text

' Hello! How can I assist you today?'

In [ ]:
from llama_index.core import Settings
Settings.llm = llm
Settings.embed_model = embed_model

## GraphRAGExtractor

The GraphRAGExtractor class is designed to extract triples (subject-relation-object) from text and enrich them by adding descriptions for entities and relationships to their properties using an LLM.

This functionality is similar to that of the `SimpleLLMPathExtractor`, but includes additional enhancements to handle entity, relationship descriptions. For guidance on implementation, you may look at similar existing [extractors](https://docs.llamaindex.ai/en/latest/examples/property_graph/Dynamic_KG_Extraction/?h=comparing).

Here's a breakdown of its functionality:

**Key Components:**

1. `llm:` The language model used for extraction.
2. `extract_prompt:` A prompt template used to guide the LLM in extracting information.
3. `parse_fn:` A function to parse the LLM's output into structured data.
4. `max_paths_per_chunk:` Limits the number of triples extracted per text chunk.
5. `num_workers:` For parallel processing of multiple text nodes.


**Main Methods:**

1. `__call__:` The entry point for processing a list of text nodes.
2. `acall:` An asynchronous version of __call__ for improved performance.
3. `_aextract:` The core method that processes each individual node.


**Extraction Process:**

For each input node (chunk of text):
1. It sends the text to the LLM along with the extraction prompt.
2. The LLM's response is parsed to extract entities, relationships, descriptions for entities and relations.
3. Entities are converted into EntityNode objects. Entity description is stored in metadata
4. Relationships are converted into Relation objects. Relationship description is stored in metadata.
5. These are added to the node's metadata under KG_NODES_KEY and KG_RELATIONS_KEY.

**NOTE:** In the current implementation, we are using only relationship descriptions. In the next implementation, we will utilize entity descriptions during the retrieval stage.

In [ ]:
import asyncio
import nest_asyncio

nest_asyncio.apply()

from typing import Any, List, Callable, Optional, Union, Dict
from IPython.display import Markdown, display

from llama_index.core.async_utils import run_jobs
from llama_index.core.indices.property_graph.utils import (
    default_parse_triplets_fn,
)
from llama_index.core.graph_stores.types import (
    EntityNode,
    KG_NODES_KEY,
    KG_RELATIONS_KEY,
    Relation,
)
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import PromptTemplate
from llama_index.core.prompts.default_prompts import (
    DEFAULT_KG_TRIPLET_EXTRACT_PROMPT,
)
from llama_index.core.schema import TransformComponent, BaseNode
from llama_index.core.bridge.pydantic import BaseModel, Field


class GraphRAGExtractor(TransformComponent):
    """Extract triples from a graph.

    Uses an LLM and a simple prompt + output parsing to extract paths (i.e. triples) and entity, relation descriptions from text.

    Args:
        llm (LLM):
            The language model to use.
        extract_prompt (Union[str, PromptTemplate]):
            The prompt to use for extracting triples.
        parse_fn (callable):
            A function to parse the output of the language model.
        num_workers (int):
            The number of workers to use for parallel processing.
        max_paths_per_chunk (int):
            The maximum number of paths to extract per chunk.
    """

    llm: LLM
    extract_prompt: PromptTemplate
    parse_fn: Callable
    num_workers: int
    max_paths_per_chunk: int

    def __init__(
        self,
        llm: Optional[LLM] = None,
        extract_prompt: Optional[Union[str, PromptTemplate]] = None,
        parse_fn: Callable = default_parse_triplets_fn,
        max_paths_per_chunk: int = 10,
        num_workers: int = 4,
    ) -> None:
        """Init params."""
        from llama_index.core import Settings

        if isinstance(extract_prompt, str):
            extract_prompt = PromptTemplate(extract_prompt)

        super().__init__(
            llm=llm or Settings.llm,
            extract_prompt=extract_prompt or DEFAULT_KG_TRIPLET_EXTRACT_PROMPT,
            parse_fn=parse_fn,
            num_workers=num_workers,
            max_paths_per_chunk=max_paths_per_chunk,
        )

    @classmethod
    def class_name(cls) -> str:
        return "GraphExtractor"

    def __call__(
        self, nodes: List[BaseNode], show_progress: bool = False, **kwargs: Any
    ) -> List[BaseNode]:
        """Extract triples from nodes."""
        return asyncio.run(
            self.acall(nodes, show_progress=show_progress, **kwargs)
        )

    async def _aextract(self, node: BaseNode) -> BaseNode:
        """Extract triples from a node."""
        assert hasattr(node, "text")

        text = node.get_content(metadata_mode="llm")
        try:
            llm_response = await self.llm.apredict(
                self.extract_prompt,
                text=text,
                max_knowledge_triplets=self.max_paths_per_chunk,
            )
            entities, entities_relationship = self.parse_fn(llm_response)
        except ValueError:
            entities = []
            entities_relationship = []

        existing_nodes = node.metadata.pop(KG_NODES_KEY, [])
        existing_relations = node.metadata.pop(KG_RELATIONS_KEY, [])
        entity_metadata = node.metadata.copy()
        for entity, entity_type, description in entities:
            entity_metadata["entity_description"] = description
            entity_node = EntityNode(
                name=entity, label=entity_type, properties=entity_metadata
            )
            existing_nodes.append(entity_node)

        relation_metadata = node.metadata.copy()
        for triple in entities_relationship:
            subj, obj, rel, description = triple
            relation_metadata["relationship_description"] = description
            rel_node = Relation(
                label=rel,
                source_id=subj,
                target_id=obj,
                properties=relation_metadata,
            )

            existing_relations.append(rel_node)

        node.metadata[KG_NODES_KEY] = existing_nodes
        node.metadata[KG_RELATIONS_KEY] = existing_relations
        return node

    async def acall(
        self, nodes: List[BaseNode], show_progress: bool = False, **kwargs: Any
    ) -> List[BaseNode]:
        """Extract triples from nodes async."""
        jobs = []
        for node in nodes:
            jobs.append(self._aextract(node))

        return await run_jobs(
            jobs,
            workers=self.num_workers,
            show_progress=show_progress,
            desc="Extracting paths from text",
        )

## GraphRAGStore

The `GraphRAGStore` class is an extension of the `Neo4jPropertyGraphStore`class, designed to implement GraphRAG pipeline. Here's a breakdown of its key components and functions:


The class uses community detection algorithms to group related nodes in the graph and then it generates summaries for each community using an LLM.


**Key Methods:**

`build_communities():`

1. Converts the internal graph representation to a NetworkX graph.

2. Applies the hierarchical Leiden algorithm for community detection.

3. Collects detailed information about each community.

4. Generates summaries for each community.

`generate_community_summary(text):`

1. Uses LLM to generate a summary of the relationships in a community.
2. The summary includes entity names and a synthesis of relationship descriptions.

`_create_nx_graph():`

1. Converts the internal graph representation to a NetworkX graph for community detection.

`_collect_community_info(nx_graph, clusters):`

1. Collects detailed information about each node based on its community.
2. Creates a string representation of each relationship within a community.

`_summarize_communities(community_info):`

1. Generates and stores summaries for each community using LLM.

`get_community_summaries():`

1. Returns the community summaries by building them if not already done.

In [ ]:
import re
import networkx as nx
from graspologic.partition import hierarchical_leiden
from collections import defaultdict

from llama_index.core.llms import ChatMessage
from llama_index.graph_stores.neo4j import Neo4jPropertyGraphStore


class GraphRAGStore(Neo4jPropertyGraphStore):
    community_summary = {}
    entity_info = None
    max_cluster_size = 5

    def generate_community_summary(self, text):
        """Generate summary for a given text using an LLM."""
        messages = [
            ChatMessage(
                role="system",
                content=(
                    "You are provided with a set of relationships from a knowledge graph, each represented as "
                    "entity1->entity2->relation->relationship_description. Your task is to create a summary of these "
                    "relationships. The summary should include the names of the entities involved and a concise synthesis "
                    "of the relationship descriptions. The goal is to capture the most critical and relevant details that "
                    "highlight the nature and significance of each relationship. Ensure that the summary is coherent and "
                    "integrates the information in a way that emphasizes the key aspects of the relationships."
                ),
            ),
            ChatMessage(role="user", content=text),
        ]
        response = llm.chat(messages)
        clean_response = re.sub(r"^assistant:\s*", "", str(response)).strip()
        return clean_response

    def build_communities(self):
        """Builds communities from the graph and summarizes them."""
        nx_graph = self._create_nx_graph()
        community_hierarchical_clusters = hierarchical_leiden(
            nx_graph, max_cluster_size=self.max_cluster_size
        )
        self.entity_info, community_info = self._collect_community_info(
            nx_graph, community_hierarchical_clusters
        )
        self._summarize_communities(community_info)

    def _create_nx_graph(self):
        """Converts internal graph representation to NetworkX graph."""
        nx_graph = nx.Graph()
        triplets = self.get_triplets()
        for entity1, relation, entity2 in triplets:
            nx_graph.add_node(entity1.name)
            nx_graph.add_node(entity2.name)
            nx_graph.add_edge(
                relation.source_id,
                relation.target_id,
                relationship=relation.label,
                description=relation.properties["relationship_description"],
            )
        return nx_graph

    def _collect_community_info(self, nx_graph, clusters):
        """
        Collect information for each node based on their community,
        allowing entities to belong to multiple clusters.
        """
        entity_info = defaultdict(set)
        community_info = defaultdict(list)

        for item in clusters:
            node = item.node
            cluster_id = item.cluster

            # Update entity_info
            entity_info[node].add(cluster_id)

            for neighbor in nx_graph.neighbors(node):
                edge_data = nx_graph.get_edge_data(node, neighbor)
                if edge_data:
                    detail = f"{node} -> {neighbor} -> {edge_data['relationship']} -> {edge_data['description']}"
                    community_info[cluster_id].append(detail)

        # Convert sets to lists for easier serialization if needed
        entity_info = {k: list(v) for k, v in entity_info.items()}

        return dict(entity_info), dict(community_info)

    def _summarize_communities(self, community_info):
        """Generate and store summaries for each community."""
        for community_id, details in community_info.items():
            details_text = (
                "\n".join(details) + "."
            )  # Ensure it ends with a period
            self.community_summary[
                community_id
            ] = self.generate_community_summary(details_text)

    def get_community_summaries(self):
        """Returns the community summaries, building them if not already done."""
        if not self.community_summary:
            self.build_communities()
        return self.community_summary

## GraphRAGQueryEngine

The GraphRAGQueryEngine class is a custom query engine designed to process queries using the GraphRAG approach. It leverages the community summaries generated by the GraphRAGStore to answer user queries. Here's a breakdown of its functionality:

**Main Components:**

`graph_store:` An instance of GraphRAGStore, which contains the community summaries.
`llm:` A Language Model (LLM) used for generating and aggregating answers.


**Key Methods:**

`custom_query(query_str: str)`

1. This is the main entry point for processing a query. It retrieves community summaries, generates answers from each summary, and then aggregates these answers into a final response.

`generate_answer_from_summary(community_summary, query):`

1. Generates an answer for the query based on a single community summary.
Uses the LLM to interpret the community summary in the context of the query.

`aggregate_answers(community_answers):`

1. Combines individual answers from different communities into a coherent final response.
2. Uses the LLM to synthesize multiple perspectives into a single, concise answer.


**Query Processing Flow:**

1. Retrieve community summaries from the graph store.
2. For each community summary, generate a specific answer to the query.
3. Aggregate all community-specific answers into a final, coherent response.


**Example usage:**

```
query_engine = GraphRAGQueryEngine(graph_store=graph_store, llm=llm)

response = query_engine.query("query")
```

In [ ]:
from llama_index.core.query_engine import CustomQueryEngine
from llama_index.core.llms import LLM
from llama_index.core import PropertyGraphIndex

import re


class GraphRAGQueryEngine(CustomQueryEngine):
    graph_store: GraphRAGStore
    index: PropertyGraphIndex
    llm: LLM
    similarity_top_k: int = 20

    def custom_query(self, query_str: str) -> str:
        """Process all community summaries to generate answers to a specific query."""

        entities = self.get_entities(query_str, self.similarity_top_k)

        community_ids = self.retrieve_entity_communities(
            self.graph_store.entity_info, entities
        )
        community_summaries = self.graph_store.get_community_summaries()
        community_answers = [
            self.generate_answer_from_summary(community_summary, query_str)
            for id, community_summary in community_summaries.items()
            if id in community_ids
        ]

        final_answer = self.aggregate_answers(community_answers)
        return final_answer

    def get_entities(self, query_str, similarity_top_k):
        nodes_retrieved = self.index.as_retriever(
            similarity_top_k=similarity_top_k
        ).retrieve(query_str)

        enitites = set()
        pattern = (
            r"^(\w+(?:\s+\w+)*)\s*->\s*([a-zA-Z\s]+?)\s*->\s*(\w+(?:\s+\w+)*)$"
        )

        for node in nodes_retrieved:
            matches = re.findall(
                pattern, node.text, re.MULTILINE | re.IGNORECASE
            )

            for match in matches:
                subject = match[0]
                obj = match[2]
                enitites.add(subject)
                enitites.add(obj)

        return list(enitites)

    def retrieve_entity_communities(self, entity_info, entities):
        """
        Retrieve cluster information for given entities, allowing for multiple clusters per entity.

        Args:
        entity_info (dict): Dictionary mapping entities to their cluster IDs (list).
        entities (list): List of entity names to retrieve information for.

        Returns:
        List of community or cluster IDs to which an entity belongs.
        """
        community_ids = []

        for entity in entities:
            if entity in entity_info:
                community_ids.extend(entity_info[entity])

        return list(set(community_ids))

    def generate_answer_from_summary(self, community_summary, query):
        """Generate an answer from a community summary based on a given query using LLM."""
        prompt = (
            f"Given the community summary: {community_summary}, "
            f"how would you answer the following query? Query: {query}"
        )
        messages = [
            ChatMessage(role="system", content=prompt),
            ChatMessage(
                role="user",
                content="I need an answer based on the above information.",
            ),
        ]
        response = self.llm.chat(messages)
        cleaned_response = re.sub(r"^assistant:\s*", "", str(response)).strip()
        return cleaned_response

    def aggregate_answers(self, community_answers):
        """Aggregate individual community answers into a final, coherent response."""
        # intermediate_text = " ".join(community_answers)
        prompt = "Combine the following intermediate answers into a final, concise response."
        messages = [
            ChatMessage(role="system", content=prompt),
            ChatMessage(
                role="user",
                content=f"Intermediate answers: {community_answers}",
            ),
        ]
        final_response = self.llm.chat(messages)
        cleaned_final_response = re.sub(
            r"^assistant:\s*", "", str(final_response)
        ).strip()
        return cleaned_final_response

##  Build End to End GraphRAG Pipeline

Now that we have defined all the necessary components, let’s construct the GraphRAG pipeline:

1. Create nodes/chunks from the text.
2. Build a PropertyGraphIndex using `GraphRAGExtractor` and `GraphRAGStore`.
3. Construct communities and generate a summary for each community using the graph built above.
4. Create a `GraphRAGQueryEngine` and begin querying.

### Create nodes/ chunks from the text.

In [ ]:
from llama_index.core.node_parser import SentenceSplitter

splitter = SentenceSplitter(
    chunk_size=1024,
    chunk_overlap=20,
)
nodes = splitter.get_nodes_from_documents(documents)

In [ ]:
len(nodes)

24

### Build ProperGraphIndex using `GraphRAGExtractor` and `GraphRAGStore`

In [ ]:
KG_TRIPLET_EXTRACT_TMPL = """
-Goal-
Given a text document, identify all entities and their entity types from the text and all relationships among the identified entities.
Given the text, extract up to {max_knowledge_triplets} entity-relation triplets.

-Steps-
1. Identify all entities. For each identified entity, extract the following information:
- entity_name: Name of the entity, capitalized
- entity_type: Type of the entity
- entity_description: Comprehensive description of the entity's attributes and activities
Format each entity as ("entity"$$$$<entity_name>$$$$<entity_type>$$$$<entity_description>)

2. From the entities identified in step 1, identify all pairs of (source_entity, target_entity) that are *clearly related* to each other.
For each pair of related entities, extract the following information:
- source_entity: name of the source entity, as identified in step 1
- target_entity: name of the target entity, as identified in step 1
- relation: relationship between source_entity and target_entity
- relationship_description: explanation as to why you think the source entity and the target entity are related to each other

Format each relationship as ("relationship"$$$$<source_entity>$$$$<target_entity>$$$$<relation>$$$$<relationship_description>)

3. When finished, output.

-Real Data-
######################
text: {text}
######################
output:"""

In [ ]:
entity_pattern = r'\("entity"\$\$\$\$"(.+?)"\$\$\$\$"(.+?)"\$\$\$\$"(.+?)"\)'
relationship_pattern = r'\("relationship"\$\$\$\$"(.+?)"\$\$\$\$"(.+?)"\$\$\$\$"(.+?)"\$\$\$\$"(.+?)"\)'


def parse_fn(response_str: str) -> Any:
    entities = re.findall(entity_pattern, response_str)
    relationships = re.findall(relationship_pattern, response_str)
    return entities, relationships


kg_extractor = GraphRAGExtractor(
    llm=llm,
    extract_prompt=KG_TRIPLET_EXTRACT_TMPL,
    max_paths_per_chunk=2,
    parse_fn=parse_fn,
)

## Docker Setup And Neo4J setup

To launch Neo4j locally, first ensure you have docker installed. Then, you can launch the database with the following docker command.

```
docker run \
    -p 7474:7474 -p 7687:7687 \
    -v $PWD/data:/data -v $PWD/plugins:/plugins \
    --name neo4j-apoc \
    -e NEO4J_apoc_export_file_enabled=true \
    -e NEO4J_apoc_import_file_enabled=true \
    -e NEO4J_apoc_import_file_use__neo4j__config=true \
    -e NEO4JLABS_PLUGINS=\[\"apoc\"\] \
    neo4j:latest
```
From here, you can open the db at http://localhost:7474/. On this page, you will be asked to sign in. Use the default username/password of neo4j and neo4j.

Once you login for the first time, you will be asked to change the password.

In [ ]:
from llama_index.graph_stores.neo4j import Neo4jPropertyGraphStore

# Note: used to be `Neo4jPGStore`
graph_store = GraphRAGStore(
    username="neo4j", password="sFRfCfMDwSPGPc8-36wnN9NtvnCpTGbL-5ALEfXY6xQ", url="neo4j+s://0892bbb1.databases.neo4j.io"
)

In [ ]:
graph_store.structured_schema

{'node_props': {'Chunk': [{'property': 'id',
    'type': 'STRING',
    'values': ['00810167-9fb6-4fb2-ba32-40d7f12c56c6',
     'f9278d88-2ada-4b2f-8326-b9c42a2a8a5a',
     'f7a76220-f97c-4c2f-8107-df49eea38bc3',
     '56daf0ed-57ea-4132-8305-4a67b432dbb6',
     '757cfdc5-c05a-435b-bcd4-7bdb3e50a64f',
     'c20cbc5e-a85b-4511-b059-a3244ceeecf4',
     'd3839a7e-3b59-45a6-9d3b-ebb15534c870',
     '87cd2cca-59ae-4eaf-85b4-40a1d8dd243a',
     '0c372884-59f8-4401-83d1-e1b18011e2e0',
     'a633689e-8e87-4636-a50d-85faece1e6d8'],
    'distinct_count': 25},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.027747511863708496,
     0.03574371710419655,
     -0.03126150369644165],
    'max_size': 1024,
    'min_size': 0},
   {'property': 'text',
    'type': 'TEXT',
    'values': ['Original papers\nWho cares for the patient diabetes?\n',
     '1984, from practice morbidity registers (eight lists',
     'P.J. Burrows, P.J. Gray, A-L. Kinmonth, et al. Origi',
     '4M 6ea *n 1a 3g ye r.-\n0 Non-insulin- Insulin- Insul',
     '* 70 (30/43) 45 (9/20) 36 (18/50)\nPractitioner group',
     'Studies are now in progress to examine\nandgeneralpra',
     'BrMedJ 1984; 288: 1055-1056.\n68 Journal of the Royal',
     'Even\nCollege (multi-stripe); Fellows (single owl); s',
     'Characteristics of Workplace\nTianweiXu,1,2,3AliceJ.C',
     '60 WorkplaceResourcesandRiskofDiabetes DiabetesCare '],
    'distinct_count': 22},
   {'property': 'document_id',
    'type': 'STRING',
    'values': ['53db3b06-eeb4-401d-b2d0-8ff1b58e3173',
     '1fb7e3b3-92cf-40a5-8797-4ddd1b9853c5',
     '77d12cb6-e0c4-4028-8038-7bc374496532',
     'b59d4437-2844-4029-9869-c86c079229c2',
     '65b1025a-060c-48c3-a78c-01c1cc3e1f61',
     '7f8bdf96-cf62-44d0-a015-301b87776a1a',
     'd5f9a94d-918a-4e8f-968d-a8cfd8f6134f',
     'f2715a99-fec5-4d2b-987f-91d4f29735ba',
     '2b67a2af-1dfa-4f53-bc49-35f18cb006c9',
     '624fc4e5-c7c6-4b5e-ae23-77d0296e4c61'],
    'distinct_count': 14},
   {'property': 'ref_doc_id',
    'type': 'STRING',
    'values': ['53db3b06-eeb4-401d-b2d0-8ff1b58e3173',
     '1fb7e3b3-92cf-40a5-8797-4ddd1b9853c5',
     '77d12cb6-e0c4-4028-8038-7bc374496532',
     'b59d4437-2844-4029-9869-c86c079229c2',
     '65b1025a-060c-48c3-a78c-01c1cc3e1f61',
     '7f8bdf96-cf62-44d0-a015-301b87776a1a',
     'd5f9a94d-918a-4e8f-968d-a8cfd8f6134f',
     'f2715a99-fec5-4d2b-987f-91d4f29735ba',
     '2b67a2af-1dfa-4f53-bc49-35f18cb006c9',
     '624fc4e5-c7c6-4b5e-ae23-77d0296e4c61'],
    'distinct_count': 14},
   {'property': '_node_type',
    'type': 'STRING',
    'values': ['TextNode', ''],
    'distinct_count': 2},
   {'property': 'doc_id',
    'type': 'STRING',
    'values': ['53db3b06-eeb4-401d-b2d0-8ff1b58e3173',
     '1fb7e3b3-92cf-40a5-8797-4ddd1b9853c5',
     '77d12cb6-e0c4-4028-8038-7bc374496532',
     'b59d4437-2844-4029-9869-c86c079229c2',
     '65b1025a-060c-48c3-a78c-01c1cc3e1f61',
     '7f8bdf96-cf62-44d0-a015-301b87776a1a',
     'd5f9a94d-918a-4e8f-968d-a8cfd8f6134f',
     'f2715a99-fec5-4d2b-987f-91d4f29735ba',
     '2b67a2af-1dfa-4f53-bc49-35f18cb006c9',
     '624fc4e5-c7c6-4b5e-ae23-77d0296e4c61'],
    'distinct_count': 14},
   {'property': '_node_content',
    'type': 'TEXT',
    'values': ['{"id_": "00810167-9fb6-4fb2-ba32-40d7f12c56c6", "emb',
     '{"id_": "f9278d88-2ada-4b2f-8326-b9c42a2a8a5a", "emb',
     '{"id_": "f7a76220-f97c-4c2f-8107-df49eea38bc3", "emb',
     '{"id_": "56daf0ed-57ea-4132-8305-4a67b432dbb6", "emb',
     '{"id_": "757cfdc5-c05a-435b-bcd4-7bdb3e50a64f", "emb',
     '{"id_": "c20cbc5e-a85b-4511-b059-a3244ceeecf4", "emb',
     '{"id_": "d3839a7e-3b59-45a6-9d3b-ebb15534c870", "emb',
     '{"id_": "87cd2cca-59ae-4eaf-85b4-40a1d8dd243a", "emb',
     '{"id_": "0c372884-59f8-4401-83d1-e1b18011e2e0", "emb',
     '{"id_": "a633689e-8e87-4636-a50d-85faece1e6d8", "emb'],
    'distinct_count': 25}],
  'Person': [{'property': 'id',
    'type': 'STRING',
    'values': ['P.J. Burrows', 'P.J. Gray', 'A-L. Kinmonth'],
    'distinct_count': 3},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.03425481170415878,
     0.020811324939131737,
     -0.0398293174803257],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['P.J. Burrows is one of the authors mentioned in the ',
     'P.J. Gray is another author mentioned in the text.',
     'A-L. Kinmonth is another author mentioned in the tex'],
    'distinct_count': 3},
   {'property': 'name',
    'type': 'STRING',
    'values': ['P.J. Burrows', 'P.J. Gray', 'A-L. Kinmonth'],
    'distinct_count': 3}],
  'Profession': [{'property': 'id',
    'type': 'STRING',
    'values': ['Doctors',
     'General Practitioners',
     'Dietitians',
     'Chiropodists'],
    'distinct_count': 4},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.021548934280872345,
     -0.017440633848309517,
     -0.02962767705321312],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Doctors are involved in setting up recall systems fo',
     'General practitioners play a crucial role in managin',
     'Dietitians provide dietary advice for managing diabe',
     'Chiropodists provide foot care services for diabetic'],
    'distinct_count': 4},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Doctors',
     'General Practitioners',
     'Dietitians',
     'Chiropodists'],
    'distinct_count': 4}],
  'Patient': [{'property': 'id',
    'type': 'STRING',
    'values': ['Patients'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.04235568642616272,
     -0.002902729669585824,
     -0.04765330255031586],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Patients include individuals receiving no regular ca'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Patients'],
    'distinct_count': 1}],
  'System': [{'property': 'id',
    'type': 'STRING',
    'values': ['Recall Systems'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.025014664977788925,
     -0.0028646045830100775,
     -0.062444642186164856],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Recall systems are set up to ensure patients receive'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Recall Systems'],
    'distinct_count': 1}],
  'Service': [{'property': 'id',
    'type': 'STRING',
    'values': ['Specialist Care'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.027488159015774727,
     -0.0033119956497102976,
     -0.03858547285199165],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Specialist care involves involvement in follow-up, p'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Specialist Care'],
    'distinct_count': 1}],
  'Medication': [{'property': 'id',
    'type': 'STRING',
    'values': ['Insulin', 'Metformin'],
    'distinct_count': 2},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.02528025209903717,
     -0.014455647207796574,
     -0.04941774159669876],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870',
     'a82d7c83-7dcd-453f-bec1-10eca8165bc8'],
    'distinct_count': 2},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Insulin is used to control blood glucose levels in s',
     'An oral antidiabetic drug used primarily to treat ty'],
    'distinct_count': 2},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Insulin', 'Metformin'],
    'distinct_count': 2}],
  'Device': [{'property': 'id',
    'type': 'STRING',
    'values': ['Blood Glucose Monitoring Sticks'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.0370122566819191,
     -0.01163529697805643,
     -0.05853383243083954],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Blood glucose monitoring sticks help monitor blood s'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Blood Glucose Monitoring Sticks'],
    'distinct_count': 1}],
  'Test': [{'property': 'id',
    'type': 'STRING',
    'values': ['Glycosylated Haemoglobin Estimations'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.058202069252729416,
     -0.0064103733748197556,
     -0.02027897723019123],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Glycosylated haemoglobin tests measure long-term blo'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Glycosylated Haemoglobin Estimations'],
    'distinct_count': 1}],
  'Medical Condition': [{'property': 'id',
    'type': 'STRING',
    'values': ['Diabetes'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.03138280287384987,
     -0.024278288707137108,
     -0.023728923872113228],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['a82d7c83-7dcd-453f-bec1-10eca8165bc8'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['A chronic condition characterized by elevated blood '],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Diabetes'],
    'distinct_count': 1}],
  'Organization': [{'property': 'id',
    'type': 'STRING',
    'values': ['NordForsk'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.04819586127996445,
     -0.0064240735955536366,
     -0.027357373386621475],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['706aa16b-a2c5-4072-bc3f-6c92e99666ed'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'STRING',
    'values': ['An organization that supports research grants.'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['NordForsk'],
    'distinct_count': 1}],
  'Study/Project': [{'property': 'id',
    'type': 'STRING',
    'values': ['DiabetesInNationalSampleOf50552Workers',
     'EGIR-NordicResearchProgrammeOnHealthAndDenmark'],
    'distinct_count': 2},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.02067490667104721,
     -0.025376711040735245,
     -0.030039632692933083],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['706aa16b-a2c5-4072-bc3f-6c92e99666ed'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['A project involving a sample of 50,552 workers aimed',
     'A longitudinal study linking survey data with regist'],
    'distinct_count': 2},
   {'property': 'name',
    'type': 'STRING',
    'values': ['DiabetesInNationalSampleOf50552Workers',
     'EGIR-NordicResearchProgrammeOnHealthAndDenmark'],
    'distinct_count': 2}],
  'Data Source': [{'property': 'id',
    'type': 'STRING',
    'values': ['RegisterData'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.044954296201467514,
     -0.012875792570412159,
     -0.035436615347862244],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['706aa16b-a2c5-4072-bc3f-6c92e99666ed'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'STRING',
    'values': ['Registry data used in studies.'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['RegisterData'],
    'distinct_count': 1}],
  'Grant': [{'property': 'id',
    'type': 'STRING',
    'values': ['AcademyOfFinlandGrants'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.052337564527988434,
     -0.007233654148876667,
     -0.010726844891905785],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['706aa16b-a2c5-4072-bc3f-6c92e99666ed'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'STRING',
    'values': ['Grants awarded by the Academy of Finland.'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['AcademyOfFinlandGrants'],
    'distinct_count': 1}],
  'Resource': [{'property': 'id',
    'type': 'STRING',
    'values': ['WorkplaceResources'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.026681765913963318,
     -0.016682138666510582,
     -0.04672549292445183],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Resources provided by an organization to its employe'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['WorkplaceResources'],
    'distinct_count': 1}],
  'Condition': [{'property': 'id',
    'type': 'STRING',
    'values': ['RiskOfDiabetes', 'ProblemDrinking', 'CardiometabolicDisease'],
    'distinct_count': 3},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.037630606442689896,
     -0.02262791618704796,
     -0.03560230880975723],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Factors or conditions that increase the likelihood o',
     'Excessive alcohol consumption leading to negative co',
     'Conditions affecting the heart and blood vessels, in'],
    'distinct_count': 3},
   {'property': 'name',
    'type': 'STRING',
    'values': ['RiskOfDiabetes', 'ProblemDrinking', 'CardiometabolicDisease'],
    'distinct_count': 3}],
  'Behavior': [{'property': 'id',
    'type': 'STRING',
    'values': ['PhysicalActivity', 'UnhealthyLifestyle'],
    'distinct_count': 2},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.012901967391371727,
     -0.01353451143950224,
     -0.053013063967227936],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Engaging in regular exercise or bodily movement for ',
     'Habits and behaviors that contribute to poor health,'],
    'distinct_count': 2},
   {'property': 'name',
    'type': 'STRING',
    'values': ['PhysicalActivity', 'UnhealthyLifestyle'],
    'distinct_count': 2}],
  'Factor': [{'property': 'id',
    'type': 'STRING',
    'values': ['JobStrain'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.04233979806303978,
     -0.014721126295626163,
     -0.03916831687092781],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Psychological demands and lack of control over one’s'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['JobStrain'],
    'distinct_count': 1}],
  'State': [{'property': 'id',
    'type': 'STRING',
    'values': ['MentalHealth'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.004421053919941187,
     -0.028026597574353218,
     -0.03796260058879852],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['State of psychological well-being and emotional stab'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['MentalHealth'],
    'distinct_count': 1}]},
 'rel_props': {'Co-Author': [{'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'relationship_description',
    'type': 'STRING',
    'values': ['Both are co-authors of original papers.'],
    'distinct_count': 1}],
  'Care Provider': [{'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'relationship_description',
    'type': 'STRING',
    'values': ['Doctors engage in setting up recall systems for diab'],
    'distinct_count': 1}],
  'Treatment': [{'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['a82d7c83-7dcd-453f-bec1-10eca8165bc8'],
    'distinct_count': 1},
   {'property': 'relationship_description',
    'type': 'STRING',
    'values': ['Metformin is commonly prescribed to manage symptoms '],
    'distinct_count': 1}],
  'Subtype': [{'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['a82d7c83-7dcd-453f-bec1-10eca8165bc8'],
    'distinct_count': 1},
   {'property': 'relationship_description',
    'type': 'STRING',
    'values': ['Type 1 Diabetes is a specific subtype of Diabetes, c'],
    'distinct_count': 1}],
  'Reduces': [{'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'relationship_description',
    'type': 'STRING',
    'values': ['Wellness programs and job training can help reduce t',
     'Regular physical activity can lower the risk of deve'],
    'distinct_count': 2}]},
 'relationships': [{'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Person'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Profession'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Patient'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'System'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Service'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Medication'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Device'},

In [ ]:
from llama_index.core import PropertyGraphIndex

index = PropertyGraphIndex(
    nodes=nodes,
    kg_extractors=[kg_extractor],
    property_graph_store=graph_store,
    show_progress=True,
)

Extracting paths from text: 100%|██████████| 24/24 [11:42<00:00, 29.29s/it]
Generating embeddings: 100%|██████████| 3/3 [00:01<00:00,  2.02it/s]
Generating embeddings: 100%|██████████| 3/3 [00:01<00:00,  2.50it/s]

In [ ]:
# index.property_graph_store.save_networkx_graph(name="./kg.html")

In [ ]:
graph_store.structured_schema

{'node_props': {'Chunk': [{'property': 'id',
    'type': 'STRING',
    'values': ['00810167-9fb6-4fb2-ba32-40d7f12c56c6',
     'f9278d88-2ada-4b2f-8326-b9c42a2a8a5a',
     'f7a76220-f97c-4c2f-8107-df49eea38bc3',
     '56daf0ed-57ea-4132-8305-4a67b432dbb6',
     '757cfdc5-c05a-435b-bcd4-7bdb3e50a64f',
     'c20cbc5e-a85b-4511-b059-a3244ceeecf4',
     'd3839a7e-3b59-45a6-9d3b-ebb15534c870',
     '87cd2cca-59ae-4eaf-85b4-40a1d8dd243a',
     '0c372884-59f8-4401-83d1-e1b18011e2e0',
     'a633689e-8e87-4636-a50d-85faece1e6d8'],
    'distinct_count': 25},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.027747511863708496,
     0.03574371710419655,
     -0.03126150369644165],
    'max_size': 1024,
    'min_size': 0},
   {'property': 'text',
    'type': 'TEXT',
    'values': ['Original papers\nWho cares for the patient diabetes?\n',
     '1984, from practice morbidity registers (eight lists',
     'P.J. Burrows, P.J. Gray, A-L. Kinmonth, et al. Origi',
     '4M 6ea *n 1a 3g ye r.-\n0 Non-insulin- Insulin- Insul',
     '* 70 (30/43) 45 (9/20) 36 (18/50)\nPractitioner group',
     'Studies are now in progress to examine\nandgeneralpra',
     'BrMedJ 1984; 288: 1055-1056.\n68 Journal of the Royal',
     'Even\nCollege (multi-stripe); Fellows (single owl); s',
     'Characteristics of Workplace\nTianweiXu,1,2,3AliceJ.C',
     '60 WorkplaceResourcesandRiskofDiabetes DiabetesCare '],
    'distinct_count': 22},
   {'property': 'document_id',
    'type': 'STRING',
    'values': ['53db3b06-eeb4-401d-b2d0-8ff1b58e3173',
     '1fb7e3b3-92cf-40a5-8797-4ddd1b9853c5',
     '77d12cb6-e0c4-4028-8038-7bc374496532',
     'b59d4437-2844-4029-9869-c86c079229c2',
     '65b1025a-060c-48c3-a78c-01c1cc3e1f61',
     '7f8bdf96-cf62-44d0-a015-301b87776a1a',
     'd5f9a94d-918a-4e8f-968d-a8cfd8f6134f',
     'f2715a99-fec5-4d2b-987f-91d4f29735ba',
     '2b67a2af-1dfa-4f53-bc49-35f18cb006c9',
     '624fc4e5-c7c6-4b5e-ae23-77d0296e4c61'],
    'distinct_count': 14},
   {'property': 'ref_doc_id',
    'type': 'STRING',
    'values': ['53db3b06-eeb4-401d-b2d0-8ff1b58e3173',
     '1fb7e3b3-92cf-40a5-8797-4ddd1b9853c5',
     '77d12cb6-e0c4-4028-8038-7bc374496532',
     'b59d4437-2844-4029-9869-c86c079229c2',
     '65b1025a-060c-48c3-a78c-01c1cc3e1f61',
     '7f8bdf96-cf62-44d0-a015-301b87776a1a',
     'd5f9a94d-918a-4e8f-968d-a8cfd8f6134f',
     'f2715a99-fec5-4d2b-987f-91d4f29735ba',
     '2b67a2af-1dfa-4f53-bc49-35f18cb006c9',
     '624fc4e5-c7c6-4b5e-ae23-77d0296e4c61'],
    'distinct_count': 14},
   {'property': '_node_type',
    'type': 'STRING',
    'values': ['TextNode', ''],
    'distinct_count': 2},
   {'property': 'doc_id',
    'type': 'STRING',
    'values': ['53db3b06-eeb4-401d-b2d0-8ff1b58e3173',
     '1fb7e3b3-92cf-40a5-8797-4ddd1b9853c5',
     '77d12cb6-e0c4-4028-8038-7bc374496532',
     'b59d4437-2844-4029-9869-c86c079229c2',
     '65b1025a-060c-48c3-a78c-01c1cc3e1f61',
     '7f8bdf96-cf62-44d0-a015-301b87776a1a',
     'd5f9a94d-918a-4e8f-968d-a8cfd8f6134f',
     'f2715a99-fec5-4d2b-987f-91d4f29735ba',
     '2b67a2af-1dfa-4f53-bc49-35f18cb006c9',
     '624fc4e5-c7c6-4b5e-ae23-77d0296e4c61'],
    'distinct_count': 14},
   {'property': '_node_content',
    'type': 'TEXT',
    'values': ['{"id_": "00810167-9fb6-4fb2-ba32-40d7f12c56c6", "emb',
     '{"id_": "f9278d88-2ada-4b2f-8326-b9c42a2a8a5a", "emb',
     '{"id_": "f7a76220-f97c-4c2f-8107-df49eea38bc3", "emb',
     '{"id_": "56daf0ed-57ea-4132-8305-4a67b432dbb6", "emb',
     '{"id_": "757cfdc5-c05a-435b-bcd4-7bdb3e50a64f", "emb',
     '{"id_": "c20cbc5e-a85b-4511-b059-a3244ceeecf4", "emb',
     '{"id_": "d3839a7e-3b59-45a6-9d3b-ebb15534c870", "emb',
     '{"id_": "87cd2cca-59ae-4eaf-85b4-40a1d8dd243a", "emb',
     '{"id_": "0c372884-59f8-4401-83d1-e1b18011e2e0", "emb',
     '{"id_": "a633689e-8e87-4636-a50d-85faece1e6d8", "emb'],
    'distinct_count': 25}],
  'Person': [{'property': 'id',
    'type': 'STRING',
    'values': ['P.J. Burrows', 'P.J. Gray', 'A-L. Kinmonth'],
    'distinct_count': 3},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.03425481170415878,
     0.020811324939131737,
     -0.0398293174803257],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['P.J. Burrows is one of the authors mentioned in the ',
     'P.J. Gray is another author mentioned in the text.',
     'A-L. Kinmonth is another author mentioned in the tex'],
    'distinct_count': 3},
   {'property': 'name',
    'type': 'STRING',
    'values': ['P.J. Burrows', 'P.J. Gray', 'A-L. Kinmonth'],
    'distinct_count': 3}],
  'Profession': [{'property': 'id',
    'type': 'STRING',
    'values': ['Doctors',
     'General Practitioners',
     'Dietitians',
     'Chiropodists'],
    'distinct_count': 4},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.021548934280872345,
     -0.017440633848309517,
     -0.02962767705321312],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Doctors are involved in setting up recall systems fo',
     'General practitioners play a crucial role in managin',
     'Dietitians provide dietary advice for managing diabe',
     'Chiropodists provide foot care services for diabetic'],
    'distinct_count': 4},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Doctors',
     'General Practitioners',
     'Dietitians',
     'Chiropodists'],
    'distinct_count': 4}],
  'Patient': [{'property': 'id',
    'type': 'STRING',
    'values': ['Patients'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.04235568642616272,
     -0.002902729669585824,
     -0.04765330255031586],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Patients include individuals receiving no regular ca'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Patients'],
    'distinct_count': 1}],
  'System': [{'property': 'id',
    'type': 'STRING',
    'values': ['Recall Systems'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.025014664977788925,
     -0.0028646045830100775,
     -0.062444642186164856],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Recall systems are set up to ensure patients receive'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Recall Systems'],
    'distinct_count': 1}],
  'Service': [{'property': 'id',
    'type': 'STRING',
    'values': ['Specialist Care'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.027488159015774727,
     -0.0033119956497102976,
     -0.03858547285199165],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Specialist care involves involvement in follow-up, p'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Specialist Care'],
    'distinct_count': 1}],
  'Medication': [{'property': 'id',
    'type': 'STRING',
    'values': ['Insulin', 'Metformin'],
    'distinct_count': 2},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.02528025209903717,
     -0.014455647207796574,
     -0.04941774159669876],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870',
     'a82d7c83-7dcd-453f-bec1-10eca8165bc8'],
    'distinct_count': 2},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Insulin is used to control blood glucose levels in s',
     'An oral antidiabetic drug used primarily to treat ty'],
    'distinct_count': 2},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Insulin', 'Metformin'],
    'distinct_count': 2}],
  'Device': [{'property': 'id',
    'type': 'STRING',
    'values': ['Blood Glucose Monitoring Sticks'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.0370122566819191,
     -0.01163529697805643,
     -0.05853383243083954],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Blood glucose monitoring sticks help monitor blood s'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Blood Glucose Monitoring Sticks'],
    'distinct_count': 1}],
  'Test': [{'property': 'id',
    'type': 'STRING',
    'values': ['Glycosylated Haemoglobin Estimations'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.058202069252729416,
     -0.0064103733748197556,
     -0.02027897723019123],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Glycosylated haemoglobin tests measure long-term blo'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Glycosylated Haemoglobin Estimations'],
    'distinct_count': 1}],
  'Medical Condition': [{'property': 'id',
    'type': 'STRING',
    'values': ['Diabetes'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.03138280287384987,
     -0.024278288707137108,
     -0.023728923872113228],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['a82d7c83-7dcd-453f-bec1-10eca8165bc8'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['A chronic condition characterized by elevated blood '],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['Diabetes'],
    'distinct_count': 1}],
  'Organization': [{'property': 'id',
    'type': 'STRING',
    'values': ['NordForsk'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.04819586127996445,
     -0.0064240735955536366,
     -0.027357373386621475],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['706aa16b-a2c5-4072-bc3f-6c92e99666ed'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'STRING',
    'values': ['An organization that supports research grants.'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['NordForsk'],
    'distinct_count': 1}],
  'Study/Project': [{'property': 'id',
    'type': 'STRING',
    'values': ['DiabetesInNationalSampleOf50552Workers',
     'EGIR-NordicResearchProgrammeOnHealthAndDenmark'],
    'distinct_count': 2},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.02067490667104721,
     -0.025376711040735245,
     -0.030039632692933083],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['706aa16b-a2c5-4072-bc3f-6c92e99666ed'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['A project involving a sample of 50,552 workers aimed',
     'A longitudinal study linking survey data with regist'],
    'distinct_count': 2},
   {'property': 'name',
    'type': 'STRING',
    'values': ['DiabetesInNationalSampleOf50552Workers',
     'EGIR-NordicResearchProgrammeOnHealthAndDenmark'],
    'distinct_count': 2}],
  'Data Source': [{'property': 'id',
    'type': 'STRING',
    'values': ['RegisterData'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.044954296201467514,
     -0.012875792570412159,
     -0.035436615347862244],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['706aa16b-a2c5-4072-bc3f-6c92e99666ed'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'STRING',
    'values': ['Registry data used in studies.'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['RegisterData'],
    'distinct_count': 1}],
  'Grant': [{'property': 'id',
    'type': 'STRING',
    'values': ['AcademyOfFinlandGrants'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.052337564527988434,
     -0.007233654148876667,
     -0.010726844891905785],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['706aa16b-a2c5-4072-bc3f-6c92e99666ed'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'STRING',
    'values': ['Grants awarded by the Academy of Finland.'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['AcademyOfFinlandGrants'],
    'distinct_count': 1}],
  'Resource': [{'property': 'id',
    'type': 'STRING',
    'values': ['WorkplaceResources'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.026681765913963318,
     -0.016682138666510582,
     -0.04672549292445183],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Resources provided by an organization to its employe'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['WorkplaceResources'],
    'distinct_count': 1}],
  'Condition': [{'property': 'id',
    'type': 'STRING',
    'values': ['RiskOfDiabetes', 'ProblemDrinking', 'CardiometabolicDisease'],
    'distinct_count': 3},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.037630606442689896,
     -0.02262791618704796,
     -0.03560230880975723],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Factors or conditions that increase the likelihood o',
     'Excessive alcohol consumption leading to negative co',
     'Conditions affecting the heart and blood vessels, in'],
    'distinct_count': 3},
   {'property': 'name',
    'type': 'STRING',
    'values': ['RiskOfDiabetes', 'ProblemDrinking', 'CardiometabolicDisease'],
    'distinct_count': 3}],
  'Behavior': [{'property': 'id',
    'type': 'STRING',
    'values': ['PhysicalActivity', 'UnhealthyLifestyle'],
    'distinct_count': 2},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.012901967391371727,
     -0.01353451143950224,
     -0.053013063967227936],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Engaging in regular exercise or bodily movement for ',
     'Habits and behaviors that contribute to poor health,'],
    'distinct_count': 2},
   {'property': 'name',
    'type': 'STRING',
    'values': ['PhysicalActivity', 'UnhealthyLifestyle'],
    'distinct_count': 2}],
  'Factor': [{'property': 'id',
    'type': 'STRING',
    'values': ['JobStrain'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.04233979806303978,
     -0.014721126295626163,
     -0.03916831687092781],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['Psychological demands and lack of control over one’s'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['JobStrain'],
    'distinct_count': 1}],
  'State': [{'property': 'id',
    'type': 'STRING',
    'values': ['MentalHealth'],
    'distinct_count': 1},
   {'property': 'embedding',
    'type': 'EMBEDDING',
    'values': [-0.004421053919941187,
     -0.028026597574353218,
     -0.03796260058879852],
    'max_size': 1024,
    'min_size': 1024},
   {'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'entity_description',
    'type': 'TEXT',
    'values': ['State of psychological well-being and emotional stab'],
    'distinct_count': 1},
   {'property': 'name',
    'type': 'STRING',
    'values': ['MentalHealth'],
    'distinct_count': 1}]},
 'rel_props': {'Co-Author': [{'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'relationship_description',
    'type': 'STRING',
    'values': ['Both are co-authors of original papers.'],
    'distinct_count': 1}],
  'Care Provider': [{'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['d3839a7e-3b59-45a6-9d3b-ebb15534c870'],
    'distinct_count': 1},
   {'property': 'relationship_description',
    'type': 'STRING',
    'values': ['Doctors engage in setting up recall systems for diab'],
    'distinct_count': 1}],
  'Treatment': [{'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['a82d7c83-7dcd-453f-bec1-10eca8165bc8'],
    'distinct_count': 1},
   {'property': 'relationship_description',
    'type': 'STRING',
    'values': ['Metformin is commonly prescribed to manage symptoms '],
    'distinct_count': 1}],
  'Subtype': [{'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['a82d7c83-7dcd-453f-bec1-10eca8165bc8'],
    'distinct_count': 1},
   {'property': 'relationship_description',
    'type': 'STRING',
    'values': ['Type 1 Diabetes is a specific subtype of Diabetes, c'],
    'distinct_count': 1}],
  'Reduces': [{'property': 'triplet_source_id',
    'type': 'STRING',
    'values': ['3e184d5b-dd49-4e80-9256-3d41a4cbae81'],
    'distinct_count': 1},
   {'property': 'relationship_description',
    'type': 'STRING',
    'values': ['Wellness programs and job training can help reduce t',
     'Regular physical activity can lower the risk of deve'],
    'distinct_count': 2}]},
 'relationships': [{'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Person'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Profession'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Patient'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'System'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Service'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Medication'},
  {'start': 'Chunk', 'type': 'MENTIONS', 'end': 'Device'},

In [ ]:
triplets = index.property_graph_store.get_triplets()
print("Total triplets:", len(triplets))

Total triplets: 10

In [ ]:
index.property_graph_store.get_triplets()[9]

[EntityNode(label='Behavior', embedding=None, properties={'id': 'PhysicalActivity', 'entity_description': 'Engaging in regular exercise or bodily movement for fitness or recreation', 'triplet_source_id': '3e184d5b-dd49-4e80-9256-3d41a4cbae81'}, name='PhysicalActivity'),
 Relation(label='Reduces', source_id='PhysicalActivity', target_id='RiskOfDiabetes', properties={'triplet_source_id': '3e184d5b-dd49-4e80-9256-3d41a4cbae81', 'relationship_description': 'Regular physical activity can lower the risk of developing type 2 diabetes.'}),
 EntityNode(label='Condition', embedding=None, properties={'id': 'RiskOfDiabetes', 'entity_description': 'Factors or conditions that increase the likelihood of developing type 2 diabetes', 'triplet_source_id': '3e184d5b-dd49-4e80-9256-3d41a4cbae81'}, name='RiskOfDiabetes')]

In [ ]:
index.property_graph_store.get_triplets()[9][0].properties

{'id': 'PhysicalActivity',
 'entity_description': 'Engaging in regular exercise or bodily movement for fitness or recreation',
 'triplet_source_id': '3e184d5b-dd49-4e80-9256-3d41a4cbae81'}

In [ ]:
retriever = index.as_retriever(
    include_text=False,  # include source text, default True
)

nodes = retriever.retrieve("What are type 1 and type 2 diabetes, and how to prevent from it?")

for node in nodes:
    print(node.text)

PhysicalActivity -> Reduces -> RiskOfDiabetes
WorkplaceResources -> Reduces -> RiskOfDiabetes
Diabetes -> Subtype -> Type 1 Diabetes
Diabetes -> Treatment -> Metformin

In [ ]:
query_engine = index.as_query_engine(
    include_text=True,
)

response = query_engine.query("What are type 1 and type 2 diabetes, and how to prevent from it?")

print(str(response))

: **Type 1 Diabetes**:
- **Definition**: Type 1 diabetes is a subtype of diabetes characterized by the body's immune system attacking and destroying the cells in the pancreas that produce insulin, leading to little or no insulin production. Insulin is essential for regulating blood sugar levels.
- **Prevention**: There is currently no known way to prevent type 1 diabetes since it is primarily caused by genetic factors and autoimmune responses.

**Type 2 Diabetes**:
- **Definition**: Type 2 diabetes is another form of diabetes where the body either does not produce enough insulin or cannot effectively use the insulin it produces (insulin resistance). This leads to elevated blood glucose levels over time.
- **Prevention**:
  - **Physical Activity**: Regular exercise can help improve insulin sensitivity and control weight, which are crucial in preventing type 2 diabetes.
  - **Healthy Lifestyle Choices**: Maintaining a balanced diet rich in fruits, vegetables, whole grains, and lean proteins while limiting processed foods and sugars can significantly reduce the risk.
  - **Weight Management**: Being overweight or obese increases the likelihood of developing type 2 diabetes. Maintaining a healthy weight through a combination of proper nutrition and regular physical activity is key.
  - **Regular Medical Check-ups**: Monitoring blood sugar levels and other health indicators can help detect early signs of diabetes and allow for timely interventions.

In summary, while type 1 diabetes cannot be prevented due to its autoimmune basis, adopting a healthier lifestyle with adequate physical activity, maintaining a balanced diet, managing weight, and undergoing regular medical check-ups can help prevent type 2 diabetes.

In [ ]:
from rich import print
print(response)

Response(
    response=": **Type 1 Diabetes**:\n- **Definition**: Type 1 diabetes is a subtype of diabetes characterized by
the body's immune system attacking and destroying the cells in the pancreas that produce insulin, leading to little
or no insulin production. Insulin is essential for regulating blood sugar levels.\n- **Prevention**: There is
currently no known way to prevent type 1 diabetes since it is primarily caused by genetic factors and autoimmune
responses.\n\n**Type 2 Diabetes**:\n- **Definition**: Type 2 diabetes is another form of diabetes where the body
either does not produce enough insulin or cannot effectively use the insulin it produces (insulin resistance). This
leads to elevated blood glucose levels over time.\n- **Prevention**: \n  - **Physical Activity**: Regular exercise
can help improve insulin sensitivity and control weight, which are crucial in preventing type 2 diabetes.\n  -
**Healthy Lifestyle Choices**: Maintaining a balanced diet rich in fruits, vegetables, whole grains, and lean
proteins while limiting processed foods and sugars can significantly reduce the risk.\n  - **Weight Management**:
Being overweight or obese increases the likelihood of developing type 2 diabetes. Maintaining a healthy weight
through a combination of proper nutrition and regular physical activity is key.\n  - **Regular Medical Check-ups**:
Monitoring blood sugar levels and other health indicators can help detect early signs of diabetes and allow for
timely interventions.\n\nIn summary, while type 1 diabetes cannot be prevented due to its autoimmune basis,
adopting a healthier lifestyle with adequate physical activity, maintaining a balanced diet, managing weight, and
undergoing regular medical check-ups can help prevent type 2 diabetes.",
    source_nodes=[
        NodeWithScore(
            node=TextNode(
                id_='a82d7c83-7dcd-453f-bec1-10eca8165bc8',
                embedding=None,
                metadata={},
                excluded_embed_metadata_keys=[],
                excluded_llm_metadata_keys=[],
                relationships={
                    <NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(
                        node_id='58d9c6ab-5a58-43f7-a2be-2a61f740cfa9',
                        node_type='4',
                        metadata={},
                        hash='d7c35db1055aa5a8e24ec3b47a29187a6d683c2bcbac8af0edd109308dfc94c4'
                    ),
                    <NodeRelationship.PREVIOUS: '2'>: RelatedNodeInfo(
                        node_id='0f588425-7c49-414e-abb9-c7b2bddf8f77',
                        node_type='1',
                        metadata={},
                        hash='2e8bcb0e6ce66983a7d347d84642b4bd10107504c79de80ce43c3e1810922f13'
                    )
                },
                metadata_template='{key}: {value}',
                metadata_separator='\n',
                text='Here are some facts extracted from the provided text:\n\nDiabetes -> Subtype -> Type 1
Diabetes\nDiabetes -> Treatment -> Metformin\n\nwith diabetes development, absence of exposure
measurementandallowed for\nOur study showed that health-related a multiplicative interaction implies the a
virtually full follow-up. People <40\nlifestyle tends to differ according to presenceofanadditiveinteraction(37).
years of age were excluded to reduce\nresource class. Stronger leadership at Additive interaction may be of better
the possibility that taking metformin\nwork could make work-related lifestyle public health relevance because it
esti- wasduetopolycysticovariansyndrome\ninterventions more successful (33). A matesthenumberofadditionaldiabetes
and the possibility of being treated by\nlongitudinal association has been found cases prevented in one group
compared insulin because of type 1 diabetes.\nbetween a high level of social capital
withanother.Forolderemployees,work- Therefore, in our study, we believe to\nand an increased probability of smoking
place psychosocial resources may con- have captured the majority of the indi-\ncessation (34). Cross-sectional
evidence tribute to selection, optimization, and viduals diagnosed with type 2 diabetes.\nhas shown that favorable
psychosocial compensationstrategiesaimedatreduc- However, because type 2 diabetes is\nworking conditions correlate
with lower ingage-relatedlosseswhilekeepingage-
morelikelytobetreatedinprimarycare\nalcoholconsumptionandhigherphysical relatedgains(38).Previousliteraturehas
andtoappearinthehealthregisterlater\nactivity(35,36). suggested health benefits as a conse- than the first time of
the diagnosis, we\nquence of intervention in any resource may have slightly underestimated
the\nPublicHealthImplications (10). The additive interaction implied association between resources and
type\nOurstudyaddstotheexistingliterature that such benefits may be most pro- 2 diabetes. Nevertheless, because
we\nby looking into the combination of nounced for organizations with a large included any health
reimbursement\nworkplacepsychosocialresourcesacross numberofolderworkers. owing to type 2 diabetes, including',
                mimetype='text/plain',
                start_char_idx=4577,
                end_char_idx=6608,
                metadata_seperator='\n',
                text_template='{metadata_str}\n\n{content}'
            ),
            score=1.0
        ),
        NodeWithScore(
            node=TextNode(
                id_='3e184d5b-dd49-4e80-9256-3d41a4cbae81',
                embedding=None,
                metadata={},
                excluded_embed_metadata_keys=[],
                excluded_llm_metadata_keys=[],
                relationships={
                    <NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(
                        node_id='8def7b05-2fbf-4c7f-bb8f-4ca0509a9eb9',
                        node_type='4',
                        metadata={},
                        hash='86984bb74a64cae71724a7c94db1184bfc0d4776c7baaf85184a74763ea26141'
                    )
                },
                metadata_template='{key}: {value}',
                metadata_separator='\n',
                text='Here are some facts extracted from the provided text:\n\nPhysicalActivity -> Reduces ->
RiskOfDiabetes\nWorkplaceResources -> Reduces -> RiskOfDiabetes\n\n66 WorkplaceResourcesandRiskofDiabetes
DiabetesCare Volume45,January2022\n28. StrainT,BrageS,SharpSJ,etal.Useofthe underlying links to disease outcomes. J
Behav stressfactorsassociatedwithproblemdrinking:a\nprevented fraction for the population to Med2006;29:377–387
studyof the Spanish working population. AmJ\ndeterminedeathsavertedbyexistingprevalence 32. Magnusson Hanson LL,
Rod NH,VahteraJ, IndMed2014;57:837–846\nof physical activity: a descriptive study. Lancet
etal.Multicohortstudyofchangeinjobstrain, 36. GriepRH,NobreAA,AlvesMGDM,etal.Job\nGlobHealth2020;8:e920–e930
poormentalhealthandincidentcardiometabolic strain and unhealthy lifestyle: results from the\n29. Hackett RA,
Steptoe A. Type 2 diabetes disease.OccupEnvironMed2019;76:785–792 baseline cohort study, Brazilian
Longitudinal\nmellitus andpsychologicalstress- amodifiable 33. MattkeS,LiuH,CaloyerasJ,etal.Workplace
StudyofAdultHealth(ELSA-Brasil).BMCPublic\nrisk factor. Nat Rev Endocrinol 2017;13:547– Wellness Programs Study:
Final Report. Rand Health2015;15:309\n560 HealthQ2013;3:7 37. VanderWeele TJ, Knol MJ. A tutorial on\n30. Gimeno D,
Tab(cid:2)ak AG, Ferrie JE, et al. 34. Kouvonen A, Oksanen T, Vahtera J, et al.
interaction.EpidemiolMethods2014;3:33–72\nJustice at work and metabolic syndrome: the
Work-placesocialcapitalandsmokingcessation: 38. Truxillo DM, Cadiz DM, Hammer LB.\nWhitehall II study. Occup
Environ Med 2010; the Finnish Public Sector Study. Addiction Supporting the aging workforce: A review
and\n67:256–262 2008;103:1857–1865 recommendations for workplace intervention\n31. Uchino BN. Social support and
health: a 35. Colell E, S(cid:2)anchez-Niubo(cid:3) A, Benavides FG, research. Ann Rev Organ Psychol Organ
Behav\nreview of physiological processes potentially Delclos GL, Domingo-Salvany A. Work-related 2015;2:351–381',
                mimetype='text/plain',
                start_char_idx=0,
                end_char_idx=1811,
                metadata_seperator='\n',
                text_template='{metadata_str}\n\n{content}'
            ),
            score=0.7800922393798828
        )
    ],
    metadata={'a82d7c83-7dcd-453f-bec1-10eca8165bc8': {}, '3e184d5b-dd49-4e80-9256-3d41a4cbae81': {}}
)

In [ ]:
response.response

": **Type 1 Diabetes**:\n- **Definition**: Type 1 diabetes is a subtype of diabetes characterized by the body's immune system attacking and destroying the cells in the pancreas that produce insulin, leading to little or no insulin production. Insulin is essential for regulating blood sugar levels.\n- **Prevention**: There is currently no known way to prevent type 1 diabetes since it is primarily caused by genetic factors and autoimmune responses.\n\n**Type 2 Diabetes**:\n- **Definition**: Type 2 diabetes is another form of diabetes where the body either does not produce enough insulin or cannot effectively use the insulin it produces (insulin resistance). This leads to elevated blood glucose levels over time.\n- **Prevention**: \n  - **Physical Activity**: Regular exercise can help improve insulin sensitivity and control weight, which are crucial in preventing type 2 diabetes.\n  - **Healthy Lifestyle Choices**: Maintaining a balanced diet rich in fruits, vegetables, whole grains, and lean proteins while limiting processed foods and sugars can significantly reduce the risk.\n  - **Weight Management**: Being overweight or obese increases the likelihood of developing type 2 diabetes. Maintaining a healthy weight through a combination of proper nutrition and regular physical activity is key.\n  - **Regular Medical Check-ups**: Monitoring blood sugar levels and other health indicators can help detect early signs of diabetes and allow for timely interventions.\n\nIn summary, while type 1 diabetes cannot be prevented due to its autoimmune basis, adopting a healthier lifestyle with adequate physical activity, maintaining a balanced diet, managing weight, and undergoing regular medical check-ups can help prevent type 2 diabetes."

In [ ]:
# index.property_graph_store.get_triplets()[10][1].properties

### Build communities

This will create communities and summary for each community.

In [ ]:
# index.property_graph_store.build_communities()

### Create QueryEngine

In [ ]:
# query_engine = GraphRAGQueryEngine(
#     graph_store=index.property_graph_store,
#     llm=llm,
#     index=index,
#     similarity_top_k=10,
# )

### Querying

In [ ]:
# response = query_engine.query(
#     "What are the main news discussed in the document?"
# )
# display(Markdown(f"{response.response}"))

In [ ]:
# response = query_engine.query("What are the main news in energy sector?")
# display(Markdown(f"{response.response}"))

## **EVALUATION**

In [ ]:
import json
import pandas as pd
from llama_index.core.evaluation import (
    FaithfulnessEvaluator,
    RelevancyEvaluator,
    CorrectnessEvaluator
)
from llama_index.llms.openai import OpenAI
import os
from tqdm import tqdm
import matplotlib.pyplot as plt

In [ ]:
# Load the evaluation dataset from the JSON file
def load_eval_dataset(json_file_path):
    with open(json_file_path, 'r') as f:
        data = [json.loads(line) for line in f.readlines()]
    return data

In [ ]:
!ollama list

/bin/bash: line 1: ollama: command not found

In [ ]:
from llama_index.llms.ollama import Ollama

# Initialize evaluation models
def init_evaluators():
    # Use GPT-4 for evaluation
    # gpt4 = OpenAI(temperature=0, model="gpt-4")
    eval_llm = Ollama(model="qwen2.5:14b", request_timeout=600.0)

    # Initialize evaluators
    faithfulness_evaluator = FaithfulnessEvaluator(llm=eval_llm)
    relevancy_evaluator = RelevancyEvaluator(llm=eval_llm)
    correctness_evaluator = CorrectnessEvaluator(llm=eval_llm)

    return faithfulness_evaluator, relevancy_evaluator, correctness_evaluator

In [ ]:
# # Function to run evaluations on a single query
# def evaluate_query(query_engine, query_data, evaluators):
#     query = query_data["question"]
#     reference = query_data["answer"]
#     context = query_data["context"]

#     # Get response from query engine
#     response = query_engine.query(query)

#     # Unpack evaluators
#     faithfulness_evaluator, relevancy_evaluator, correctness_evaluator = evaluators

#     # Evaluate faithfulness
#     faith_result = faithfulness_evaluator.evaluate_response(response=response)

#     # Evaluate relevancy of response to query
#     relevancy_result = relevancy_evaluator.evaluate_response(query=query, response=response)

#     # Evaluate relevancy of each source node if available
#     source_relevancy_results = []
#     if hasattr(response, 'source_nodes') and response.source_nodes:
#         for source_node in response.source_nodes:
#             node_result = relevancy_evaluator.evaluate(
#                 query=query,
#                 response=str(response),
#                 contexts=[source_node.get_content()]
#             )
#             source_relevancy_results.append(node_result.passing)

#         # Calculate percentage of relevant sources
#         source_relevancy_score = sum(source_relevancy_results) / len(source_relevancy_results)
#     else:
#         source_relevancy_score = None

#     # Evaluate correctness against reference answer
#     correctness_result = correctness_evaluator.evaluate(
#         query=query,
#         response=str(response),
#         reference=reference
#     )

#     # Return all evaluation results
#     return {
#         "query": query,
#         "response": str(response),
#         "reference": reference,
#         "faithfulness_score": 1 if faith_result.passing else 0,
#         "faithfulness_feedback": faith_result.feedback,
#         "relevancy_score": 1 if relevancy_result.passing else 0,
#         "relevancy_feedback": relevancy_result.feedback,
#         "source_relevancy_score": source_relevancy_score,
#         "correctness_score": correctness_result.score,
#         "correctness_passing": 1 if correctness_result.passing else 0,
#         "correctness_feedback": correctness_result.feedback
#     }

In [ ]:
# Function to run evaluations on a single query
def evaluate_query(query_engine, query_data, evaluators):
    query = query_data["question"]
    reference = query_data["answer"]
    context = query_data["context"]

    # Get response from query engine
    response = query_engine.query(query)

    # Extract the response text from the Response object
    # This handles the specific format of your query engine's response
    if hasattr(response, 'response'):
        response_text = response.response
    else:
        response_text = str(response)

    # Unpack evaluators
    faithfulness_evaluator, relevancy_evaluator, correctness_evaluator = evaluators

    # Evaluate faithfulness - pass the full Response object
    # LlamaIndex evaluators can handle the Response object directly
    faith_result = faithfulness_evaluator.evaluate_response(response=response)

    # Evaluate relevancy of response to query
    # For relevancy, we need to explicitly pass the text content
    relevancy_result = relevancy_evaluator.evaluate(
        query=query,
        response=response_text,
        contexts=[context]  # Use the context from the dataset
    )

    # Evaluate relevancy of each source node if available
    source_relevancy_results = []
    if hasattr(response, 'source_nodes') and response.source_nodes:
        for source_node in response.source_nodes:
            # Extract source content properly
            if hasattr(source_node, 'node') and hasattr(source_node.node, 'text'):
                source_content = source_node.node.text
            else:
                source_content = str(source_node)

            node_result = relevancy_evaluator.evaluate(
                query=query,
                response=response_text,
                contexts=[source_content]
            )
            source_relevancy_results.append(node_result.passing)

        # Calculate percentage of relevant sources
        source_relevancy_score = sum(source_relevancy_results) / len(source_relevancy_results)
    else:
        source_relevancy_score = None

    # Evaluate correctness against reference answer
    correctness_result = correctness_evaluator.evaluate(
        query=query,
        response=response_text,
        reference=reference
    )

    # Return all evaluation results
    return {
        "query": query,
        "response": response_text,
        "reference": reference,
        "faithfulness_score": 1 if faith_result.passing else 0,
        "faithfulness_feedback": faith_result.feedback,
        "relevancy_score": 1 if relevancy_result.passing else 0,
        "relevancy_feedback": relevancy_result.feedback,
        "source_relevancy_score": source_relevancy_score,
        "correctness_score": correctness_result.score,
        "correctness_passing": 1 if correctness_result.passing else 0,
        "correctness_feedback": correctness_result.feedback
    }

In [ ]:
# Function to create visualizations
def create_visualizations(results_df, metrics):
    # Create a bar chart for metrics
    plt.figure(figsize=(10, 6))
    bars = plt.bar(list(metrics.keys()), list(metrics.values()))
    plt.ylim(0, 1.1)
    plt.title('RAG System Evaluation Metrics')
    plt.ylabel('Score')
    plt.xticks(rotation=45)

    # Add values on top of bars
    for bar in bars:
        height = bar.get_height()
        if height is not None:  # Handle None values
            plt.text(bar.get_x() + bar.get_width()/2., height + 0.05,
                    f'{height:.2f}', ha='center', va='bottom')

    plt.tight_layout()
    plt.savefig('rag_evaluation_metrics.png')
    plt.close()

    # Create detailed metric breakdowns if needed
    if 'correctness_score' in results_df.columns:
        plt.figure(figsize=(10, 6))
        plt.hist(results_df['correctness_score'], bins=10, alpha=0.7)
        plt.title('Distribution of Correctness Scores')
        plt.xlabel('Score')
        plt.ylabel('Count')
        plt.savefig('correctness_distribution.png')
        plt.close()

In [ ]:
# Main evaluation function
def evaluate_rag_system(query_engine, dataset_path):
    # Load dataset
    eval_dataset = load_eval_dataset(dataset_path)
    print(f"Loaded {len(eval_dataset)} evaluation samples")

    # Initialize evaluators
    evaluators = init_evaluators()

    # Run evaluations for each query in the dataset
    results = []
    for query_data in tqdm(eval_dataset, desc="Evaluating queries"):
        try:
            result = evaluate_query(query_engine, query_data, evaluators)
            results.append(result)
        except Exception as e:
            print(f"Error evaluating query '{query_data['question']}': {str(e)}")

    # Convert results to DataFrame
    results_df = pd.DataFrame(results)

    # Calculate aggregate metrics
    metrics = {
        "Faithfulness": results_df["faithfulness_score"].mean(),
        "Relevancy": results_df["relevancy_score"].mean(),
        "Source Relevancy": results_df["source_relevancy_score"].dropna().mean() if not results_df["source_relevancy_score"].dropna().empty else None,
        "Correctness Score": results_df["correctness_score"].mean(),
        "Correctness Pass Rate": results_df["correctness_passing"].mean()
    }

    # Create a metrics summary DataFrame
    metrics_df = pd.DataFrame({
        "Metric": list(metrics.keys()),
        "Score": list(metrics.values())
    })

    # Generate visualizations
    create_visualizations(results_df, metrics)

    return results_df, metrics_df

In [ ]:
# Main execution function for the RAG evaluation
def run_rag_evaluation(query_engine, dataset_path="./mini_medical_qa_dataset.jsonl"):
    print("Starting RAG system evaluation...")

    # Run the evaluation
    results_df, metrics_df = evaluate_rag_system(query_engine, dataset_path)

    # Save detailed results to CSV
    results_df.to_csv("rag_evaluation_detailed_results.csv", index=False)

    # Display the metrics summary
    print("\nRAG Evaluation Summary:")
    print(metrics_df.to_string(index=False))

    print("\nDetailed results saved to 'rag_evaluation_detailed_results.csv'")
    print("Visualizations saved as PNG files")

    return results_df, metrics_df

In [ ]:
# Example usage (uncomment to run)
if __name__ == "__main__":
    # Assuming your query_engine and dataset are ready
    results_df, metrics_df = run_rag_evaluation(query_engine, "./mini_medical_qa_dataset.jsonl")

Starting RAG system evaluation...

Loaded 20 evaluation samples

Evaluating queries: 100%|██████████| 20/20 [11:45<00:00, 35.30s/it]

RAG Evaluation Summary:

               Metric    Score
         Faithfulness 0.000000
            Relevancy 0.150000
     Source Relevancy 0.361111
    Correctness Score 1.050000
Correctness Pass Rate 0.000000

Detailed results saved to 'rag_evaluation_detailed_results.csv'

Visualizations saved as PNG files

In [ ]:
metrics_df

                  Metric     Score
0           Faithfulness  0.000000
1              Relevancy  0.150000
2       Source Relevancy  0.361111
3      Correctness Score  1.050000
4  Correctness Pass Rate  0.000000

In [ ]:
metrics_df

                  Metric  Score
0           Faithfulness   0.00
1              Relevancy   0.15
2       Source Relevancy   0.30
3      Correctness Score   1.15
4  Correctness Pass Rate   0.05

In [ ]:
results_df

,query,response,reference,faithfulness_score,faithfulness_feedback,relevancy_score,relevancy_feedback,source_relevancy_score,correctness_score,correctness_passing,correctness_feedback
0,What is the primary factor that predicts outco...,":\nGiven the new context provided, it is still...",Self-management competence,0,NO\n\nThe provided text does not contain infor...,1,"YES\n\nThe response provided, while not direct...",0.00,2.0,0,The generated answer provides a detailed expla...
1,What is the relationship between stress and me...,Empty Response,Social competence and parental support are med...,0,Empty Response,0,"NO\n\nThe response is empty, but the context p...",NaN,1.0,0,The generated answer does not provide any rele...
2,What is a key factor that influences adherence...,Empty Response,Psychosocial variables and metabolic control.,0,Empty Response,0,"NO\n\nThe response to the query ""What is a key...",NaN,1.0,0,The generated answer does not provide any info...
3,What is the mean raw score for youths ≥11 year...,": Based on the provided context, there is stil...",21.9 ± 3.6,0,NO\n\nThe provided context discusses Paul Grah...,0,NO\n\nThe context provided includes data relat...,0.00,1.0,0,The generated answer is completely irrelevant ...
4,What is the mean raw score for youths ≥11 year...,: The provided context does not contain any in...,12.4 ± 2.9,0,NO,0,NO\n\nThe context provided does actually conta...,1.00,1.0,0,The generated answer is not relevant because i...
5,What is the mean maximum score for youths aged...,: The provided context does not contain any in...,12,0,NO,0,NO\n\nThe response correctly states that the p...,1.00,1.0,0,The generated answer is completely irrelevant ...
6,What is the mean adherence score of the DSMP-F...,: The information provided does not contain an...,86,0,NO,0,NO\n\nThe response provided does not align wit...,0.00,1.0,0,The generated answer is not relevant to the us...
7,What is the mean adherence score of the DSMP-F...,": Based on the provided context, there is stil...",73% of the maximum DSMP total score (86),0,NO\n\nThe additional text provided does not co...,1,YES\n\nThe response accurately reflects that t...,1.00,1.0,0,The generated answer is entirely irrelevant to...
8,What is the mean adherence score of parents an...,:\nThe provided context does not contain any i...,73% of the maximum DSMP total score (86),0,NO\n\nThe additional text provided does not co...,1,YES\n\nThe response acknowledges that the cont...,0.25,1.0,0,The generated answer is not relevant because i...
9,What is the name of the modified structured in...,Empty Response,Diabetes Self-Management Profile for Flexible ...,0,Empty Response,0,"NO\n\nThe response to the query is empty, whil...",NaN,1.0,0,The generated answer is completely empty and d...
10,What is the name of the study group that modif...,Empty Response,The Diabetes Research in Children Network (Dir...,0,Empty Response,0,"NO\n\nThe response to the query is empty, wher...",NaN,1.0,0,The generated answer is completely empty and d...
11,What is the name of the modified structured in...,Empty Response,Diabetes Self-Management Profile for Flexible ...,0,Empty Response,0,"NO\n\nThe response is empty, while the query a...",NaN,1.0,0,The generated answer does not provide any rele...
12,What is the purpose of a technical review in d...,Empty Response,A technical review provides a balanced review ...,0,Empty Response,0,NO\n\nThe response to the query is empty and d...,NaN,1.0,0,The generated answer does not provide any info...
13,What is the purpose of a technical review in d...,Empty Response,A technical review provides a scientific ratio...,0,Empty Response,0,"NO\n\nThe response to the query ""What is the p...",NaN,1.0,0,The generated answer does not provide any rele...
14,What is the typical cause of severe metabolic ...,Empty Response,Diabetic ketoacidosis: the usual villain or a ...,0,Empty Response,0,NO\n\nThe response to the query is empty and d...,NaN,1.0,0,The generated answer does not address the user...
15,What is the term for severe metabolic acidosis...,Empty Response,Diabetic ketoacidosis,0,Empty Response,0,NO\n\nThe response to the query is empty and d...,NaN,1.0,0,The generated answer does not provide any info...
16,What is the term for severe metabolic acidosis...,Empty Response,Diabetic ketoacidosis: the usual villain or a ...,0,Empty Response,0,NO\n\nThe response is not in line with the con...,NaN,1.0,0,The generated answer does not provide any info...
17,What is the relationship between drug use and ...,Empty Response,Drug users tend to have a greater gap between ...,0,Empty Response,0,NO\n\nThe response provided is an empty respon...,NaN,1.0,0,The generated answer is an empty response and ...
18,What is the calculated acidosis-ketosis gap (A...,prarosa\n\nIt appears that the provided contex...,3.6 mmol/l,0,NO\n\nThe provided context does not contain an...,0,"NO\n\nThe response ""prarosa"" does not address ...",0.00,1.0,0,The generated answer is completely irrelevant ...
19,What is the calculated acidosis-ketosis gap (A...,"Based on the context information provided, th...","3.6 mmol/l vs. 2.5 mmol/l, P = 0.0004",0,NO,0,NO\n\nThe response does not accurately reflect...,0.00,1.0,0,The generated answer is completely irrelevant ...